package ci

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// parse runs the generated bytes through a real YAML parser, so a test that
// asserts on structure is asserting on what a runner would actually load —
// not on a substring of a string we happened to build.
func parse(t *testing.T, provider string) map[string]any {
	t.Helper()
	_, content, err := Generate(provider)
	if err != nil {
		t.Fatalf("Generate(%q): %v", provider, err)
	}
	var doc map[string]any
	if err := yaml.Unmarshal(content, &doc); err != nil {
		t.Fatalf("generated %s pipeline is not valid YAML: %v\n\n%s", provider, err, content)
	}
	return doc
}

// runStep returns the shell body of the step that invokes `tortureu run`,
// pulled out of the parsed document rather than out of the template.
func runStep(t *testing.T, provider string) string {
	t.Helper()
	doc := parse(t, provider)
	switch provider {
	case ProviderGitHub:
		jobs, ok := doc["jobs"].(map[string]any)
		if !ok {
			t.Fatalf("workflow has no jobs: mapping: %#v", doc["jobs"])
		}
		for _, j := range jobs {
			job, ok := j.(map[string]any)
			if !ok {
				t.Fatalf("job is not a mapping: %#v", j)
			}
			steps, ok := job["steps"].([]any)
			if !ok {
				t.Fatalf("job has no steps: list: %#v", job["steps"])
			}
			for _, s := range steps {
				step, _ := s.(map[string]any)
				if body, _ := step["run"].(string); strings.Contains(body, "tortureu run") {
					return body
				}
			}
		}
	case ProviderGitLab:
		for name, v := range doc {
			job, ok := v.(map[string]any)
			if !ok {
				continue // stages:, variables:, ... — not a job
			}
			lines, ok := job["script"].([]any)
			if !ok {
				continue
			}
			var b strings.Builder
			for _, l := range lines {
				fmt.Fprintf(&b, "%v\n", l)
			}
			if strings.Contains(b.String(), "tortureu run") {
				t.Logf("gitlab job under test: %s", name)
				return b.String()
			}
		}
	}
	t.Fatalf("no step in the generated %s pipeline invokes `tortureu run`", provider)
	return ""
}

// spec: R-CLI-11
func TestGeneratedGitHubWorkflowHasAJobWithStepsThatRunTortureu(t *testing.T) {
	doc := parse(t, ProviderGitHub)

	// `on:` is the trigger key. A YAML 1.1 parser folds the bare key to the
	// boolean true (PyYAML does; yaml.v3 does not), so the document is
	// re-parsed with an any-keyed map and either spelling is accepted —
	// asserting on one parser's quirk would prove nothing about the file.
	_, content, err := Generate(ProviderGitHub)
	if err != nil {
		t.Fatal(err)
	}
	var loose map[any]any
	if err := yaml.Unmarshal(content, &loose); err != nil {
		t.Fatal(err)
	}
	if _, ok := loose["on"]; !ok {
		if _, ok := loose[true]; !ok {
			t.Errorf("workflow declares no trigger (`on:`): keys %v", keys(doc))
		}
	}
	if _, ok := doc["name"].(string); !ok {
		t.Errorf("workflow has no name: %#v", doc["name"])
	}

	jobs, ok := doc["jobs"].(map[string]any)
	if !ok || len(jobs) == 0 {
		t.Fatalf("workflow declares no jobs: %#v", doc["jobs"])
	}
	for name, j := range jobs {
		job, ok := j.(map[string]any)
		if !ok {
			t.Fatalf("job %s is not a mapping", name)
		}
		if _, ok := job["runs-on"].(string); !ok {
			t.Errorf("job %s has no runs-on:", name)
		}
		steps, ok := job["steps"].([]any)
		if !ok || len(steps) == 0 {
			t.Errorf("job %s has no steps:", name)
		}
		for i, s := range steps {
			step, ok := s.(map[string]any)
			if !ok {
				t.Fatalf("job %s step %d is not a mapping", name, i)
			}
			_, hasRun := step["run"]
			_, hasUses := step["uses"]
			if !hasRun && !hasUses {
				t.Errorf("job %s step %d has neither run: nor uses: — a runner would reject it", name, i)
			}
		}
	}

	if runStep(t, ProviderGitHub) == "" {
		t.Error("no step runs tortureu")
	}
}

// spec: R-CLI-11
//
// GitLab's documented schema: top-level `stages:` is a list, every job names
// a `stage:` drawn from it, and `script:` is a list of shell lines. A job
// naming a stage that does not exist is a pipeline GitLab refuses to create.
func TestGeneratedGitLabPipelineMatchesGitLabSchemaKeys(t *testing.T) {
	doc := parse(t, ProviderGitLab)

	stagesAny, ok := doc["stages"].([]any)
	if !ok || len(stagesAny) == 0 {
		t.Fatalf("no top-level stages: list: %#v", doc["stages"])
	}
	stages := map[string]bool{}
	for _, s := range stagesAny {
		stages[fmt.Sprint(s)] = true
	}

	jobs := 0
	for name, v := range doc {
		job, ok := v.(map[string]any)
		if !ok {
			continue
		}
		if _, isJob := job["script"]; !isJob {
			continue
		}
		jobs++
		if strings.HasPrefix(name, ".") {
			continue // hidden template job
		}
		stage, _ := job["stage"].(string)
		if !stages[stage] {
			t.Errorf("job %s names stage %q, which is not in stages: %v", name, stage, stagesAny)
		}
		if _, ok := job["script"].([]any); !ok {
			t.Errorf("job %s script: is not a list: %#v", name, job["script"])
		}
		if _, ok := job["image"]; !ok {
			t.Errorf("job %s declares no image:", name)
		}
		// R-CLI-11: a failing resilience run must fail the build.
		if af, present := job["allow_failure"]; present && af != false {
			t.Errorf("job %s sets allow_failure: %v — a resilience failure must fail the build", name, af)
		}
	}
	if jobs == 0 {
		t.Fatal("pipeline declares no job with a script:")
	}
}

// spec: R-CLI-11
//
// The contract is not "the YAML mentions the codes" — it is that the emitted
// shell actually behaves this way. So the script is extracted from the parsed
// document and executed by a real shell against a stub `tortureu` that exits
// with each code in turn. What is asserted is what CI would observe: the code
// survives to the step's own exit status (never flattened to a generic 1),
// and each code is reported by its own distinct meaning.
func TestGeneratedScriptPropagatesEachExitCodeDistinctly(t *testing.T) {
	for _, provider := range Providers() {
		for _, shell := range []string{"bash", "sh"} {
			for code := 0; code <= 5; code++ {
				t.Run(fmt.Sprintf("%s/%s/%d", provider, shell, code), func(t *testing.T) {
					out, status := runScript(t, shell, runStep(t, provider), code)
					if status != code {
						t.Errorf("stub tortureu exited %d, script exited %d — the code must be propagated, not flattened\n%s", code, status, out)
					}
					want := map[int]string{
						0: "pass",
						1: "assertion",
						2: "adapter",
						3: "egress",
						4: "ambiguous",
						5: "UNEXPECTED",
					}[code]
					if !strings.Contains(out, want) {
						t.Errorf("exit %d reported as %q, want it to mention %q (VERDICT.md §2 meaning)", code, strings.TrimSpace(out), want)
					}
				})
			}
		}
	}
}

// spec: R-CLI-11
//
// Distinct means distinct: no two codes may produce the same report, or the
// pipeline has flattened them in substance while listing them in form.
func TestGeneratedScriptReportsAreUnique(t *testing.T) {
	for _, provider := range Providers() {
		seen := map[string]int{}
		for code := 0; code <= 4; code++ {
			out, _ := runScript(t, "bash", runStep(t, provider), code)
			out = strings.TrimSpace(out)
			if prev, dup := seen[out]; dup {
				t.Errorf("%s: exit %d and exit %d report identically: %q", provider, prev, code, out)
			}
			seen[out] = code
		}
	}
}

// spec: R-CLI-11 (no continue-on-error / allow_failure escape hatch on the run step)
func TestGeneratedPipelinesDoNotExcuseFailure(t *testing.T) {
	for _, provider := range Providers() {
		_, content, err := Generate(provider)
		if err != nil {
			t.Fatal(err)
		}
		for _, forbidden := range []string{"continue-on-error: true", "allow_failure: true", "|| true"} {
			if strings.Contains(string(content), forbidden) {
				t.Errorf("%s pipeline contains %q — a resilience failure must fail the build", provider, forbidden)
			}
		}
		// `exit 0` as a command (not "(exit 0)" inside a message) would
		// hand CI a green regardless of the verdict.
		if m := regexp.MustCompile(`(?m)^\s*exit 0\s*$`).FindString(string(content)); m != "" {
			t.Errorf("%s pipeline hard-codes a successful exit: %q", provider, m)
		}
	}
}

// spec: R-CLI-11
func TestGenerateRejectsUnknownProviderListingWhatIsSupported(t *testing.T) {
	_, _, err := Generate("jenkins")
	if err == nil {
		t.Fatal("Generate(\"jenkins\") succeeded; want an error naming the supported providers")
	}
	for _, p := range Providers() {
		if !strings.Contains(err.Error(), p) {
			t.Errorf("error %q does not list supported provider %q", err, p)
		}
	}
}

// spec: R-CLI-11
func TestDefaultPathsAreTheConventionalOnes(t *testing.T) {
	want := map[string]string{
		ProviderGitHub: filepath.Join(".github", "workflows", "tortureu.yml"),
		ProviderGitLab: ".gitlab-ci.yml",
	}
	for provider, path := range want {
		got, _, err := Generate(provider)
		if err != nil {
			t.Fatal(err)
		}
		if got != path {
			t.Errorf("Generate(%q) path = %q, want %q", provider, got, path)
		}
	}
}

// runScript executes body with `tortureu` stubbed to exit with code, and
// returns the combined output and the script's own exit status.
func runScript(t *testing.T, shell, body string, code int) (string, int) {
	t.Helper()
	dir := t.TempDir()
	stub := filepath.Join(dir, "tortureu")
	script := fmt.Sprintf("#!/bin/sh\nexit %d\n", code)
	if err := os.WriteFile(stub, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(shell, "-c", body)
	cmd.Env = append(os.Environ(), "PATH="+dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	out, err := cmd.CombinedOutput()
	status := 0
	if err != nil {
		ee, ok := err.(*exec.ExitError)
		if !ok {
			t.Fatalf("running generated script with %s: %v\n%s", shell, err, out)
		}
		status = ee.ExitCode()
	}
	return string(out), status
}

func keys(m map[string]any) []string {
	var out []string
	for k := range m {
		out = append(out, k)
	}
	return out
}
