// Async/security-domain emit targets (SPEC.md R-CLI-8 proposed), added
// alongside the pumba/netem/iptables/protocol group. Each registers itself
// from this file's own init() (never editing emit.go's shared dispatch, per
// the concurrent-agent convention documented in emit.go and protocol.go),
// and each reuses internal/config + internal/fault rather than re-deriving
// fault semantics (R-CLI-8).
//
// Symbols here are prefixed "attack" to stay clear of the other files this
// package is being extended with concurrently.
//
// VERIFICATION STATUS (recorded per R-PROC "verify against the real thing"):
//
//   - slowloris: VERIFIED. slowhttptest 1.8.2 was installed and its exact
//     flag set (-H -c -r -i -l -u, and the -X slow-read flags -k/-n) was
//     run for real against a live nginx container on this host; it held 100
//     concurrent slow-header connections open for the whole test window.
//     The connection count/interval are documented defaults (torture.yaml
//     carries no such knob) and are labelled as such in the output.
//
//   - rebalance: VERIFIED against a live redpandadata/redpanda broker on
//     this host. The emitted form — "docker run --rm --network
//     container:<broker> redpandadata/redpanda topic consume <topic> -X
//     brokers=127.0.0.1:9092 -g <group> --offset end", bounded by
//     `timeout` — joined a consumer group and was killed on timeout;
//     repeated cycles created the group and churned its membership (each
//     join and each departure is a rebalance under the Kafka group
//     protocol). rpk was verified against Redpanda specifically; it speaks
//     the same wire protocol to Apache Kafka but that was NOT separately
//     re-verified here.
//
//   - dlq-test (kafka): VERIFIED against the same broker. Flood-producing to
//     a topic with a bounded retention.bytes drove its log-start-offset
//     forward (retention.bytes≈2MiB evicted ~186k of 350k produced
//     messages) — that eviction of the oldest dead letters IS the overflow
//     this models. The flood-produce sidecar form ("docker run --network
//     container:<broker> --entrypoint /bin/sh redpandadata/redpanda -c '...
//     | rpk topic produce ...'") was run for real.
//
//   - dlq-test (sqs): NOT VERIFIED. No SQS/LocalStack or AWS credentials
//     were available at authoring time. The aws sqs send-message flags are
//     from the AWS CLI reference, not an executed run; the output header
//     says so.
package emit

import (
	"fmt"
	"strings"

	"github.com/jd316/tortureu/internal/config"
	"github.com/jd316/tortureu/internal/detect"
)

// attackBrokerImage is the image whose rpk is used to reach a Kafka-compatible
// broker. rpk speaks the Kafka protocol, so it works against Apache Kafka too
// (see the package VERIFICATION STATUS for what was actually run).
const attackBrokerImage = "redpandadata/redpanda:latest"

func init() {
	// slowloris works from torture.yaml alone (it targets target.base_url);
	// rebalance and dlq-test need a real dependency address from detection
	// and must refuse rather than guess a broker/queue; fixtures needs the
	// detected language to pick a library.
	Register("slowloris", func(cfg *config.Config, _ *detect.System) (string, error) { return attackSlowloris(cfg) }, false)
	Register("rebalance", attackRebalance, true)
	Register("dlq-test", attackDLQ, true)
	Register("fixtures", attackFixtures, true)
}

// ---------------------------------------------------------------------
// slowloris — slowhttptest (registry.yaml: always)
// ---------------------------------------------------------------------

// attackSlowlorisConns is a documented default connection count. It is NOT
// derived from torture.yaml — the schema carries no such knob — so it is
// emitted with a comment saying to tune it. 500 is enough to exhaust a
// default worker/thread pool on a small service.
const attackSlowlorisConns = 500

const attackSlowlorisDefaultLen = 240 // slowhttptest's own default test length

const attackSlowlorisHeader = `#!/usr/bin/env bash
# Generated by tortureu emit slowloris. Requires: slowhttptest (v1.8.x;
# e.g. "apt-get install slowhttptest").
#
# DEFENSIVE CAPACITY SELF-TEST OF YOUR OWN SERVICE. This targets the SUT you
# declared in torture.yaml (target.base_url) and measures how your own
# server holds up under slow-request resource exhaustion (Slowloris /
# R-U-Dead-Yet / Slow Read). It is not an attack on anyone else — run it
# only against a system you operate.
#
# The connection count and interval are documented defaults, NOT derived
# from torture.yaml (its schema has no such knob) — tune them to your SUT.
#
# VERIFIED against slowhttptest 1.8.2: this flag set was run for real
# against a live server and held its connections open for the whole window.
#
# at:/for: on faults are NOT scheduled here — delegate tier (real output,
# separate timing, registry.yaml).
`

// attackSlowloris renders slowhttptest commands aimed at the operator's own
// SUT (target.base_url). Registry when: always, so it has no fault-verb gate;
// it still reports every torture.yaml fault as not translated (R-CLI-8),
// since a slow-request load tool emits request traffic, not fault injection.
func attackSlowloris(cfg *config.Config) (string, error) {
	var b strings.Builder
	b.WriteString(attackSlowlorisHeader)

	url := attackSlowlorisURL(cfg.Target.BaseURL)
	if url == "" {
		b.WriteString("\n# tortureu emit slowloris: target.base_url is not set in torture.yaml,\n")
		b.WriteString("# so there is no SUT URL to test; nothing to emit (base_url is not guessed).\n")
		return b.String(), nil
	}

	length := attackSlowlorisDefaultLen
	sizedFromLoad := false
	if total, ok := totalSeconds(cfg.Load); ok && total > 0 {
		length = total
		sizedFromLoad = true
	}

	b.WriteString("\n")
	if sizedFromLoad {
		fmt.Fprintf(&b, "# -l %d sized from load.stages' total duration.\n", length)
	} else {
		fmt.Fprintf(&b, "# -l %d is slowhttptest's default (no load.stages duration to size from).\n", length)
	}
	fmt.Fprintf(&b, "# -c %d connections is a documented default, not from torture.yaml — tune it.\n", attackSlowlorisConns)

	b.WriteString("\n# slow headers (Slowloris):\n")
	fmt.Fprintf(&b, "slowhttptest -H -c %d -r 200 -i 10 -l %d -u %s\n", attackSlowlorisConns, length, url)
	b.WriteString("\n# slow POST body (R-U-Dead-Yet):\n")
	fmt.Fprintf(&b, "slowhttptest -B -c %d -r 200 -i 10 -l %d -u %s\n", attackSlowlorisConns, length, url)
	b.WriteString("\n# slow read (Slow Read):\n")
	fmt.Fprintf(&b, "slowhttptest -X -c %d -r 200 -i 10 -l %d -k 3 -n 1 -u %s\n", attackSlowlorisConns, length, url)

	// Report every fault as not translated (R-CLI-8), reusing the shared
	// checkFaults so the verb table is the one internal/fault owns.
	faultsOut, err := checkFaults("slowloris", cfg)
	if err != nil {
		return "", err
	}
	if faultsOut != "" {
		b.WriteString("\n# faults declared in torture.yaml's faults: block (not applicable to a\n# slow-request load tool; use tortureu emit pumba/netem/iptables instead):\n")
		b.WriteString(faultsOut)
	}
	return b.String(), nil
}

// attackSlowlorisURL normalises base_url into slowhttptest's -u argument: a
// single trailing slash on the path, matching slowhttptest's own default
// ("http://localhost/"). Returns "" when base_url is empty.
func attackSlowlorisURL(baseURL string) string {
	if baseURL == "" {
		return ""
	}
	scheme, rest, ok := strings.Cut(baseURL, "://")
	if !ok {
		return baseURL
	}
	if !strings.Contains(rest, "/") {
		return scheme + "://" + rest + "/"
	}
	return baseURL
}

// ---------------------------------------------------------------------
// rebalance — rebalance-storm (registry.yaml: dep:kafka)
// ---------------------------------------------------------------------

const attackRebalanceHeader = `#!/usr/bin/env bash
# Generated by tortureu emit rebalance. Requires: docker. Reaches the
# detected kafka broker through "--network container:<broker>" (the same
# reasoning as tortureu emit sysbench/memtier: borrow the broker's network
# namespace instead of guessing a compose network or a published port),
# driving it with rpk from the ` + attackBrokerImage + ` image — rpk speaks
# the Kafka protocol, so it also works against Apache Kafka.
#
# REBALANCE STORM: a transient consumer repeatedly joins the target consumer
# group and is killed mid-batch by "timeout", so the group rebalances on
# every join and every departure — "kill consumers mid-batch, repeatedly"
# (registry.yaml).
#
# The consumer GROUP and TOPIC are NOT in torture.yaml's schema and are NOT
# guessed — set the CHANGE_ME placeholders below to your app's real consumer
# group id and a topic that group subscribes to.
#
# VERIFIED against a live redpandadata/redpanda broker on this host: this
# exact bounded-join form joined a consumer group and left on kill, and
# repeated cycles created the group and churned its membership.
#
# at:/for: on faults are NOT scheduled here — delegate tier.
`

// attackRebalance drives a Kafka rebalance storm against the detected kafka
// broker (registry.yaml when: dep:kafka). It refuses (noDepNote) rather than
// guess a broker when none is detected, and never guesses the consumer group
// or topic (R-CLI-8 honesty over coverage).
func attackRebalance(cfg *config.Config, sys *detect.System) (string, error) {
	dep, ok := findDep(sys, "kafka")
	if !ok {
		return noDepNote("rebalance", sys, "kafka"), nil
	}
	port := attackBrokerPort(dep.Address)

	var b strings.Builder
	b.WriteString(attackRebalanceHeader)
	b.WriteString("\nGROUP=CHANGE_ME    # your app's real consumer group id\n")
	b.WriteString("TOPIC=CHANGE_ME    # a topic that group subscribes to\n")
	b.WriteString("CYCLES=20          # number of join/leave cycles (the \"storm\")\n")
	b.WriteString("HOLD=4             # seconds each transient consumer stays in the group before it is killed\n\n")
	b.WriteString("for i in $(seq 1 \"$CYCLES\"); do\n")
	fmt.Fprintf(&b, "  timeout \"$HOLD\" docker run --rm --network container:%s %s \\\n", dep.Name, attackBrokerImage)
	fmt.Fprintf(&b, "    topic consume \"$TOPIC\" -X brokers=127.0.0.1:%s -g \"$GROUP\" --offset end >/dev/null 2>&1\n", port)
	b.WriteString("  echo \"rebalance cycle $i: consumer joined $GROUP then was killed mid-batch (leave)\"\n")
	b.WriteString("done\n")
	return b.String(), nil
}

// ---------------------------------------------------------------------
// dlq-test — dlq-overflow (registry.yaml: dep:kafka|dep:sqs)
// ---------------------------------------------------------------------

const attackDLQKafkaHeader = `#!/usr/bin/env bash
# Generated by tortureu emit dlq-test (kafka). Requires: docker. Reaches the
# detected kafka broker the same way tortureu emit rebalance does (see that
# tool's header), using rpk from the ` + attackBrokerImage + ` image.
#
# DLQ OVERFLOW: floods the dead-letter topic until its retention evicts the
# oldest messages — "what happens when the DLQ itself fills" (registry.yaml).
# A DLQ topic with a bounded retention.bytes silently drops its oldest dead
# letters once full, so anything that later expects to replay the whole DLQ
# loses those records.
#
# The DLQ TOPIC is NOT in torture.yaml's schema and is NOT guessed — set
# DLQ_TOPIC to your real dead-letter topic.
#
# VERIFIED against a live redpandadata/redpanda broker on this host:
# flood-producing via this form with a bounded retention.bytes drove the
# topic's log-start-offset forward (oldest messages evicted), which IS the
# overflow this models.
#
# at:/for: on faults are NOT scheduled here — delegate tier.
`

const attackDLQSQSHeader = `#!/usr/bin/env bash
# Generated by tortureu emit dlq-test (sqs). Requires: the aws CLI.
#
# DLQ OVERFLOW: SQS has no size cap, so "overflow" here means the DLQ growing
# unbounded because nothing drains it — dead letters then age out at the
# queue's retention limit (max 14 days) and are silently lost. This floods
# the DLQ so you can watch your alerting / retention behaviour.
#
# The DLQ queue URL is NOT derivable — dep:sqs is detected from the lockfile
# only, and SQS is AWS-hosted with no address in your compose — and is NOT
# guessed. Set DLQ_URL. Point --endpoint-url at LocalStack to keep this off
# real AWS.
#
# VERIFICATION STATUS: NOT verified against a live SQS/LocalStack on this
# host (none was available at authoring time). The aws sqs send-message
# flags are from the AWS CLI reference, not an executed run — verify before
# relying on it.
#
# at:/for: on faults are NOT scheduled here — delegate tier.
`

// attackDLQ floods a dead-letter destination to overflow it. It prefers a
// detected kafka broker, falls back to a detected sqs client, and refuses
// (naming both dependency types) when neither is present (registry.yaml
// when: dep:kafka|dep:sqs).
func attackDLQ(cfg *config.Config, sys *detect.System) (string, error) {
	if dep, ok := findDep(sys, "kafka"); ok {
		return attackDLQKafka(dep), nil
	}
	if _, ok := findDep(sys, "sqs"); ok {
		return attackDLQSQS(), nil
	}
	return attackDLQNoDepNote(sys), nil
}

func attackDLQKafka(dep detect.Dep) string {
	port := attackBrokerPort(dep.Address)
	var b strings.Builder
	b.WriteString(attackDLQKafkaHeader)
	b.WriteString("\nDLQ_TOPIC=CHANGE_ME    # your real dead-letter topic\n")
	b.WriteString("COUNT=1000000          # messages to flood into the DLQ\n\n")
	b.WriteString("# 1) bound the DLQ's retention so it can actually overflow (skip if already bounded):\n")
	fmt.Fprintf(&b, "docker run --rm --network container:%s %s \\\n", dep.Name, attackBrokerImage)
	fmt.Fprintf(&b, "  topic alter-config \"$DLQ_TOPIC\" -X brokers=127.0.0.1:%s --set retention.bytes=2097152\n\n", port)
	b.WriteString("# 2) flood the DLQ (oldest dead letters get evicted once retention.bytes is exceeded):\n")
	fmt.Fprintf(&b, "docker run --rm --network container:%s --entrypoint /bin/sh -e DLQ_TOPIC -e COUNT %s -c \\\n", dep.Name, attackBrokerImage)
	fmt.Fprintf(&b, "  'for i in $(seq 1 \"$COUNT\"); do echo \"dlq-overflow-$i\"; done | rpk topic produce \"$DLQ_TOPIC\" -X brokers=127.0.0.1:%s -z snappy'\n", port)
	return b.String()
}

func attackDLQSQS() string {
	var b strings.Builder
	b.WriteString(attackDLQSQSHeader)
	b.WriteString("\nDLQ_URL=CHANGE_ME               # your dead-letter queue URL\n")
	b.WriteString("ENDPOINT=http://localhost:4566  # LocalStack; remove --endpoint-url below for real AWS\n")
	b.WriteString("COUNT=100000                    # messages to flood into the DLQ\n\n")
	b.WriteString("for i in $(seq 1 \"$COUNT\"); do\n")
	b.WriteString("  aws sqs send-message --endpoint-url \"$ENDPOINT\" --queue-url \"$DLQ_URL\" --message-body \"dlq-overflow-$i\" >/dev/null\n")
	b.WriteString("done\n")
	return b.String()
}

// attackDLQNoDepNote mirrors noDepNote but names both dependency types this
// tool accepts, keeping the nil-sys ("detection failed") case distinct from
// the "no such dependency" case (R-COV-6).
func attackDLQNoDepNote(sys *detect.System) string {
	if sys == nil {
		return "# tortureu emit dlq-test: the system could not be detected, so no kafka or sqs address is known; nothing to emit.\n"
	}
	return "# tortureu emit dlq-test: no kafka or sqs dependency was detected (dep:kafka|dep:sqs); nothing to emit.\n"
}

// attackBrokerPort extracts the broker port from a detected dependency
// address, defaulting to Kafka's 9092 when none was derivable.
func attackBrokerPort(address string) string {
	if _, port := hostPort(address); port != "" {
		return port
	}
	return "9092"
}
