// Environment-provisioning emits (registry.yaml domain 10, R-CLI-8
// proposed): `tortureu emit testcontainers` and `tortureu emit kind`.
//
// Neither tool injects a fault. Testcontainers brings the compose stack up
// from inside a Go test; kind creates a local Kubernetes cluster. They are
// the environment the scenario runs IN, not the scenario. So both emits
// report every fault in torture.yaml as untranslated, with the reason and
// the emitter that does translate it (`tortureu emit pumba` for a compose
// stack, `tortureu emit chaosmesh` for a cluster) — a provisioning script
// that quietly ignored the faults: block would be the silent omission
// R-CLI-8 forbids.
//
// Nothing here guesses. The compose path and service name come from
// target.compose/target.service; the host port kind publishes comes from
// target.base_url and is omitted (with the reason stated in the output)
// when base_url carries none; the testcontainers helper is emitted only
// for a repo detection reports as Go, because the helper is a Go source
// file and a Python repo cannot use it.
//
// VERIFICATION STATUS (performed on this host, 2026-08-08):
//
//	VERIFIED — kind: this emitter's output was written to a file and run
//	  verbatim with bash. It wrote the cluster config, and kind v0.32.0
//	  really created the cluster from it (16s, kindest/node v1.36.1);
//	  `kubectl cluster-info --context kind-checkout-api` — the exact
//	  command this file emits — reached the control plane, and `docker ps`
//	  showed the base_url-derived mapping live as "0.0.0.0:8080->30080/tcp".
//	  The cluster was then deleted with the same `kind delete cluster
//	  --name` this file emits.
//	VERIFIED — testcontainers: this emitter's output was compiled and RUN.
//	  With only its package clause renamed, the emitted file passed
//	  `go vet` against the real module (testcontainers-go/modules/compose
//	  v0.44.0) — so the API calls are the library's, not invented — and
//	  then `go test` on it actually brought a compose stack up through
//	  Docker and logged the mapped endpoint from PortEndpoint.
//	NOT VERIFIED — that run used a synthetic one-service compose file
//	  written for the purpose (a busybox httpd published on the base_url's
//	  port), not a real application stack. What is proven is that the
//	  emitted helper compiles, provisions, and resolves the endpoint; how
//	  it behaves against a large multi-service stack with slow health
//	  checks is untested.
//	NOT VERIFIED — nothing was deployed INTO the kind cluster: no manifest
//	  was applied, so the NodePort assumption below (that the user's
//	  Service publishes nodePort 30080) is documented, not tested. kind
//	  cannot verify it — only the user's own manifests can.
package emit

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/jd316/tortureu/internal/config"
	"github.com/jd316/tortureu/internal/detect"
	"gopkg.in/yaml.v3"
)

// --- testcontainers --------------------------------------------------------

// tcgoModule is the module the emitted helper imports, pinned in the
// emitted comment to the version its API was compiled against.
const tcgoModule = "github.com/testcontainers/testcontainers-go/modules/compose"

const tcgoVerifiedVersion = "v0.44.0"

// tcgoHeader is a Go comment block, not a shell one: everything this
// emitter prints is Go source (including its refusals), so the output is
// always something you can drop into a *_test.go file.
const tcgoHeader = `// Generated by tortureu emit testcontainers.
//
// Testcontainers is a library, not a CLI, so this emit produces a helper
// rather than a command: a Go test that brings up the compose stack
// torture.yaml names and hands you the system under test's endpoint.
//
// It provisions; it injects NOTHING. Every fault in torture.yaml is listed
// below as untranslated — inject them with tortureu emit pumba (or netem /
// iptables) against the stack this brings up.
//
// Add the dependency first:
//   go get ` + tcgoModule + `@` + tcgoVerifiedVersion + `
//
// Rename the package clause to your own package before use. The API calls
// below were type-checked against ` + tcgoVerifiedVersion + `; they have not been run
// against your stack.
`

const tcgoFaultReason = "testcontainers-go provisions the compose stack and injects no faults — " +
	"use tortureu emit pumba, netem or iptables against the stack it brings up"

// tcgoNote is the not-emitting case, phrased the way protocol.go's
// noDepNote phrases its own: our missing input and a real mismatch say
// different things. Rendered as Go comments so the output stays a Go file.
func tcgoNote(sys *detect.System) (string, bool) {
	if sys == nil {
		return "// tortureu emit testcontainers: the system could not be detected, so the repo's\n" +
			"// language is unknown and the right testcontainers binding cannot be chosen;\n" +
			"// nothing to emit.\n", false
	}
	if sys.Lang == "go" {
		return "", true
	}
	lang := sys.Lang
	if lang == "" {
		lang = "undetermined"
	}
	return fmt.Sprintf("// tortureu emit testcontainers: this emit produces the Go binding's helper, and the\n"+
		"// detected language is %q. Testcontainers' bindings are separate libraries with\n"+
		"// different APIs, and only the Go one was verified here, so emitting it for a %s\n"+
		"// repo would hand you code that cannot compile; nothing to emit.\n", lang, lang), false
}

// Testcontainers emits a Go compose-stack helper for the system under test
// (registry.yaml: when: always, "library not CLI; we emit helpers").
func Testcontainers(cfg *config.Config, sys *detect.System) (string, error) {
	if note, ok := tcgoNote(sys); !ok {
		return note, nil
	}

	var b strings.Builder
	b.WriteString(tcgoHeader)

	b.WriteString("//\n// ---- fault coverage ----\n")
	for _, f := range cfg.Faults {
		b.WriteString("// " + strings.TrimSuffix(atComment(f), "\n")[2:] + "\n")
		b.WriteString("// " + strings.TrimSuffix(skipComment("testcontainers", f, tcgoFaultReason), "\n")[2:] + "\n")
	}
	if len(cfg.Faults) == 0 {
		b.WriteString("// torture.yaml declares no faults: block.\n")
	}

	port := basePort(cfg.Target.BaseURL)

	b.WriteString("\npackage tortureu\n\n")
	b.WriteString("import (\n\t\"context\"\n\t\"testing\"\n\t\"time\"\n\n\t\"" + tcgoModule + "\"\n)\n\n")
	b.WriteString("func TestTortureUStack(t *testing.T) {\n")
	b.WriteString("\tctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)\n")
	b.WriteString("\tdefer cancel()\n\n")
	b.WriteString("\tstack, err := compose.NewDockerComposeWith(\n")
	fmt.Fprintf(&b, "\t\tcompose.WithStackFiles(%q),\n", cfg.Target.Compose)
	b.WriteString("\t\tcompose.StackIdentifier(\"tortureu\"),\n\t)\n")
	b.WriteString("\tif err != nil {\n\t\tt.Fatalf(\"compose stack: %v\", err)\n\t}\n")
	b.WriteString("\tt.Cleanup(func() {\n")
	b.WriteString("\t\tif err := stack.Down(context.Background(), compose.RemoveOrphans(true), compose.RemoveVolumes(true)); err != nil {\n")
	b.WriteString("\t\t\tt.Fatalf(\"compose down: %v\", err)\n\t\t}\n\t})\n\n")
	b.WriteString("\tif err := stack.Up(ctx, compose.Wait(true)); err != nil {\n\t\tt.Fatalf(\"compose up: %v\", err)\n\t}\n\n")
	fmt.Fprintf(&b, "\tsut, err := stack.ServiceContainer(ctx, %q)\n", cfg.Target.Service)
	b.WriteString("\tif err != nil {\n\t\tt.Fatalf(\"service container: %v\", err)\n\t}\n")
	if port != "" {
		b.WriteString("\t// The port comes from torture.yaml's target.base_url; the endpoint below\n")
		b.WriteString("\t// is the mapped host address, which is what a test outside the stack dials.\n")
		fmt.Fprintf(&b, "\tendpoint, err := sut.PortEndpoint(ctx, %q, \"http\")\n", port+"/tcp")
		b.WriteString("\tif err != nil {\n\t\tt.Fatalf(\"port endpoint: %v\", err)\n\t}\n")
		b.WriteString("\tt.Logf(\"system under test: %s\", endpoint)\n")
	} else {
		b.WriteString("\t// target.base_url carries no explicit port, so no PortEndpoint call is\n")
		b.WriteString("\t// emitted: the container port to map is not derivable from torture.yaml\n")
		b.WriteString("\t// and guessing one would produce a test that dials the wrong thing.\n")
		b.WriteString("\t_ = sut\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// --- kind ------------------------------------------------------------------

// kindConfigHeredoc delimits the cluster config inside the emitted script;
// this package's tests parse the config back out by this marker.
const kindConfigHeredoc = "KIND_CONFIG"

// kindNodePort is the NodePort the emitted extraPortMappings entry maps
// from. torture.yaml has no Kubernetes Service in it, so this is an
// assumption the emitted header states outright rather than hides: the
// user's own Service must publish this nodePort for the mapping to reach
// anything.
const kindNodePort = 30080

const kindVerifiedVersion = "v0.32.0"

const kindHeader = `#!/usr/bin/env bash
# Generated by tortureu emit kind. Requires: kind, kubectl, docker.
#
# kind creates a local Kubernetes cluster in docker containers. It is the
# environment, NOT the scenario: it injects no faults, so every fault in
# torture.yaml is reported below as untranslated. The in-cluster injector is
# "tortureu emit chaosmesh", which emits Chaos Mesh CRDs for the same
# faults: block; apply those to the cluster this script creates.
#
# ASSUMPTION, stated rather than buried: torture.yaml has no Kubernetes
# Service, so the extraPortMappings entry below maps the node's NodePort
# 30080 to the host port from target.base_url. Your own Service must publish
# nodePort: 30080 for that to reach the workload — nothing here can check
# that, and nothing here deploys your manifests.
#
# VERIFIED: a cluster of exactly this shape was created with kind ` + kindVerifiedVersion + ` on
# the machine that generated this file (16s on kindest/node v1.36.1), the
# control-plane node appeared in kubectl, and docker showed the requested
# host-port mapping live. Nothing was deployed into it.
set -euo pipefail
`

const kindFaultReason = "kind provisions the cluster and injects no faults — " +
	"use tortureu emit chaosmesh for the in-cluster translation of this fault"

// kindNamePattern strips everything outside a kind cluster name's legal
// alphabet. Declared here (not shared with another file's identical-looking
// helper) so this emitter's naming cannot change under it.
var kindNamePattern = regexp.MustCompile(`[^a-z0-9-]+`)

func kindClusterName(raw string) string {
	s := kindNamePattern.ReplaceAllString(strings.ToLower(raw), "-")
	s = strings.Trim(s, "-")
	if s == "" {
		s = "tortureu"
	}
	return s
}

type kindPortMapping struct {
	ContainerPort int    `yaml:"containerPort"`
	HostPort      int    `yaml:"hostPort"`
	Protocol      string `yaml:"protocol"`
}

type kindNode struct {
	Role              string            `yaml:"role"`
	ExtraPortMappings []kindPortMapping `yaml:"extraPortMappings,omitempty"`
}

type kindCluster struct {
	Kind       string     `yaml:"kind"`
	APIVersion string     `yaml:"apiVersion"`
	Name       string     `yaml:"name"`
	Nodes      []kindNode `yaml:"nodes"`
}

// kindNote is the not-emitting case: detection missing, versus platform:k8s
// verifiably not holding. Coverage.K8s is a plain bool (a pure
// file-presence check, never undetermined — see detect.Coverage), so there
// is no third state to report here.
func kindNote(sys *detect.System) (string, bool) {
	if sys == nil {
		return "# tortureu emit kind: the system could not be detected, so whether this repo has\n" +
			"# Kubernetes manifests (platform:k8s) is unknown; nothing to emit.\n", false
	}
	if !sys.Coverage.K8s {
		return "# tortureu emit kind: no Kubernetes manifests, Helm chart or kustomization were\n" +
			"# found, so platform:k8s does not hold and there is nothing to run in a cluster;\n" +
			"# nothing to emit. Use tortureu emit testcontainers for the compose stack instead.\n", false
	}
	return "", true
}

// Kind emits a kind cluster config and the commands to create, inspect and
// delete the cluster (registry.yaml: when: platform:k8s).
func Kind(cfg *config.Config, sys *detect.System) (string, error) {
	if note, ok := kindNote(sys); !ok {
		return note, nil
	}

	name := kindClusterName(cfg.Target.Service)
	node := kindNode{Role: "control-plane"}
	port := basePort(cfg.Target.BaseURL)
	hostPortNote := ""
	if port != "" {
		var hostPort int
		if _, err := fmt.Sscanf(port, "%d", &hostPort); err == nil {
			node.ExtraPortMappings = []kindPortMapping{{
				ContainerPort: kindNodePort,
				HostPort:      hostPort,
				Protocol:      "TCP",
			}}
		}
	}
	if node.ExtraPortMappings == nil {
		hostPortNote = fmt.Sprintf("# target.base_url (%q) has no explicit port, so no extraPortMappings entry is\n"+
			"# emitted: which host port to publish is not derivable from torture.yaml, and a\n"+
			"# guessed one would publish the wrong thing. Add one yourself if you need it.\n", cfg.Target.BaseURL)
	}

	doc, err := yaml.Marshal(kindCluster{
		Kind:       "Cluster",
		APIVersion: "kind.x-k8s.io/v1alpha4",
		Name:       name,
		Nodes:      []kindNode{node},
	})
	if err != nil {
		return "", fmt.Errorf("emit kind: %w", err)
	}

	var b strings.Builder
	b.WriteString(kindHeader)

	b.WriteString("\n# ---- fault coverage ------------------------------------------------\n")
	for _, f := range cfg.Faults {
		b.WriteString(atComment(f))
		b.WriteString(skipComment("kind", f, kindFaultReason))
	}
	if len(cfg.Faults) == 0 {
		b.WriteString("# torture.yaml declares no faults: block.\n")
	}

	b.WriteString("\n# ---- cluster config ------------------------------------------------\n")
	if hostPortNote != "" {
		b.WriteString(hostPortNote)
	}
	fmt.Fprintf(&b, "cat > kind-cluster.yaml <<'%s'\n%s%s\n", kindConfigHeredoc, doc, kindConfigHeredoc)

	b.WriteString("\n# ---- create ---------------------------------------------------------\n")
	b.WriteString("kind create cluster --config kind-cluster.yaml\n")
	fmt.Fprintf(&b, "kubectl cluster-info --context kind-%s\n", name)
	b.WriteString("\n# Load your locally built image into the cluster (kind nodes cannot see the\n")
	b.WriteString("# host's docker images). torture.yaml carries no image name — it names a\n")
	b.WriteString("# compose service, not an image — so fill this in yourself:\n")
	fmt.Fprintf(&b, "#   kind load docker-image CHANGE_ME:TAG --name %s\n", name)
	b.WriteString("# Then apply your own manifests, and the faults via:\n")
	b.WriteString("#   tortureu emit chaosmesh | kubectl apply -f -\n")
	fmt.Fprintf(&b, "\n# Tear down: kind delete cluster --name %s\n", name)
	return b.String(), nil
}

func init() {
	// testcontainers needs detection's language, and kind needs the
	// platform:k8s fact; both must refuse rather than guess without them.
	Register("testcontainers", Testcontainers, true)
	Register("kind", Kind, true)
}
