package emit

import (
	"fmt"
	"hash/fnv"
	"strings"

	"github.com/jd316/tortureu/internal/config"
	"github.com/jd316/tortureu/internal/detect"
)

// fixtures — gofakeit (lang:go) / faker (lang:python|lang:js), registry.yaml.
//
// One registered verb ("fixtures", registered in attack.go's init); the
// library is chosen from the detected language, never defaulted. When the
// language is not detected the tool says so and emits no library code rather
// than guessing one (R-CLI-8 honesty over coverage, R-COV-6).
//
// VERIFICATION STATUS: all three emitted programs were run for real on this
// host with the seed embedding below and printed DETERMINISTIC records
// across two runs of the same seed:
//   - Go:     gofakeit v7 (gofakeit.New(seed).UUID/Name/Email) — compiled and run.
//   - Python: Faker (Faker.seed(n); fake.uuid4/name/email) — run under python:3.12.
//   - JS:     @faker-js/faker (faker.seed(n); string.uuid/person.fullName/
//             internet.email) — run under node:20.
// The record shape (id/name/email) is a STARTER: torture.yaml carries no
// schema, so the emitted code says to edit it to the app's real tables.

// attackFixtures picks the fixtures library from the detected language and
// emits a deterministic generator seeded from torture.yaml's reset.seed
// (D-8: deterministic start state). sys carries the detected language.
func attackFixtures(cfg *config.Config, sys *detect.System) (string, error) {
	lang := ""
	if sys != nil {
		lang = sys.Lang
	}
	seed, seedNote := fixturesSeed(cfg)

	switch lang {
	case "go":
		return fixturesGo(seed, seedNote), nil
	case "python":
		return fixturesPython(seed, seedNote), nil
	case "node":
		return fixturesJS(seed, seedNote), nil
	default:
		return fixturesUndetected(), nil
	}
}

// fixturesSeed derives a stable 32-bit seed from reset.seed so every run
// produces identical fixtures. Kept to 32 bits so the same number is exact
// across Go (uint64), Python (int) and JS (a double-backed number).
func fixturesSeed(cfg *config.Config) (seed uint32, note string) {
	h := fnv.New32a()
	if cfg.Reset.Seed != "" {
		_, _ = h.Write([]byte(cfg.Reset.Seed))
		return h.Sum32(), fmt.Sprintf("seeded from torture.yaml's reset.seed (%q)", cfg.Reset.Seed)
	}
	_, _ = h.Write([]byte("tortureu-default"))
	return h.Sum32(), "reset.seed is not set in torture.yaml — using a fixed default seed; set reset.seed for reproducible fixtures"
}

func fixturesGo(seed uint32, seedNote string) string {
	var b strings.Builder
	b.WriteString("// Generated by tortureu emit fixtures (detected language: go -> gofakeit).\n")
	b.WriteString("// Requires: go get github.com/brianvoe/gofakeit/v7\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Deterministic (D-8): %s.\n", seedNote)
	b.WriteString("// The Record shape is a STARTER — torture.yaml carries no schema, so edit\n")
	b.WriteString("// it to match your real tables.\n")
	b.WriteString("//\n")
	b.WriteString("// VERIFIED: compiled and run against gofakeit v7 on this host; identical\n")
	b.WriteString("// output across runs of the same seed.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n\t\"encoding/json\"\n\t\"os\"\n\n\t\"github.com/brianvoe/gofakeit/v7\"\n)\n\n")
	b.WriteString("type Record struct {\n")
	b.WriteString("\tID    string `json:\"id\"`\n")
	b.WriteString("\tName  string `json:\"name\"`\n")
	b.WriteString("\tEmail string `json:\"email\"`\n")
	b.WriteString("}\n\n")
	b.WriteString("func main() {\n")
	fmt.Fprintf(&b, "\tfaker := gofakeit.New(%d)\n", seed)
	b.WriteString("\tenc := json.NewEncoder(os.Stdout)\n")
	b.WriteString("\tfor i := 0; i < 100; i++ {\n")
	b.WriteString("\t\t_ = enc.Encode(Record{\n")
	b.WriteString("\t\t\tID:    faker.UUID(),\n")
	b.WriteString("\t\t\tName:  faker.Name(),\n")
	b.WriteString("\t\t\tEmail: faker.Email(),\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

func fixturesPython(seed uint32, seedNote string) string {
	var b strings.Builder
	b.WriteString("\"\"\"\n")
	b.WriteString("Generated by tortureu emit fixtures (detected language: python -> Faker).\n")
	b.WriteString("Requires: pip install Faker\n\n")
	fmt.Fprintf(&b, "Deterministic (D-8): %s.\n", seedNote)
	b.WriteString("The record shape is a STARTER — torture.yaml carries no schema, so edit it\n")
	b.WriteString("to match your real tables.\n\n")
	b.WriteString("VERIFIED: run against a real Faker on this host; identical output across\n")
	b.WriteString("runs of the same seed.\n")
	b.WriteString("\"\"\"\n")
	b.WriteString("import json\n")
	b.WriteString("from faker import Faker\n\n")
	b.WriteString("fake = Faker()\n")
	fmt.Fprintf(&b, "Faker.seed(%d)\n\n", seed)
	b.WriteString("for _ in range(100):\n")
	b.WriteString("    print(json.dumps({\n")
	b.WriteString("        \"id\": fake.uuid4(),\n")
	b.WriteString("        \"name\": fake.name(),\n")
	b.WriteString("        \"email\": fake.email(),\n")
	b.WriteString("    }))\n")
	return b.String()
}

func fixturesJS(seed uint32, seedNote string) string {
	var b strings.Builder
	b.WriteString("// Generated by tortureu emit fixtures (detected language: js -> @faker-js/faker).\n")
	b.WriteString("// Requires: npm install @faker-js/faker  (ESM; run with `node fixtures.mjs`)\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Deterministic (D-8): %s.\n", seedNote)
	b.WriteString("// The record shape is a STARTER — torture.yaml carries no schema, so edit it\n")
	b.WriteString("// to match your real tables.\n")
	b.WriteString("//\n")
	b.WriteString("// VERIFIED: run against @faker-js/faker on this host; identical output across\n")
	b.WriteString("// runs of the same seed.\n")
	b.WriteString("import { faker } from '@faker-js/faker';\n\n")
	fmt.Fprintf(&b, "faker.seed(%d);\n\n", seed)
	b.WriteString("for (let i = 0; i < 100; i++) {\n")
	b.WriteString("  console.log(JSON.stringify({\n")
	b.WriteString("    id: faker.string.uuid(),\n")
	b.WriteString("    name: faker.person.fullName(),\n")
	b.WriteString("    email: faker.internet.email(),\n")
	b.WriteString("  }));\n")
	b.WriteString("}\n")
	return b.String()
}

// fixturesUndetected refuses to pick a library when detection found no
// language, rather than defaulting to one (R-CLI-8, R-COV-6). It names the
// candidates as prose but emits none of their import forms.
func fixturesUndetected() string {
	return "# tortureu emit fixtures: the language was not detected from your lockfile,\n" +
		"# so the fixtures library is unknown (gofakeit for Go, Faker for Python/JS)\n" +
		"# — nothing emitted (a library is not guessed). Add a lockfile detection can\n" +
		"# read, or run tortureu emit fixtures against a project whose language is detected.\n"
}
