// ghz — gRPC load generation (R-CLI-8 proposed; registry.yaml: tier
// delegate, when: spec:proto, how: "tortureu emit ghz").
//
// VERIFICATION STATUS (what this file's author actually ran, and what they
// did not):
//
//   - VERIFIED for real, on this machine: every ghz flag this emitter
//     writes was executed by the real ghz binary (docker image
//     ghcr.io/bojand/ghz:latest) against a live gRPC server
//     (moul/grpcbin, joined via --network container:). Three shapes were
//     run: (1) constant rate, "--rps=50 --duration=5s" -> 249 responses at
//     49.58 req/s, all [OK]; (2) the ramp-up line schedule,
//     "--load-schedule=line --load-start=10 --load-end=50 --load-step=4
//     --load-step-duration=1s --duration=10s" -> 279 responses averaging
//     27.9 req/s (the mean of a 10->50 ramp, as expected); (3) the same
//     line schedule descending with a NEGATIVE --load-step (-4, 50->10)
//     -> 319 responses averaging 31.6 req/s. A --proto/--call invocation
//     against a real .proto file baked into an image was also run
//     ("--proto /proto/hello.proto --call hello.HelloService/SayHello -d
//     '{...}' --concurrency=5") and produced real responses.
//     TestGhz_EmittedScriptRunsAgainstRealGRPCServer re-runs the whole
//     emitted script end-to-end under TORTUREU_DOCKER_TESTS=1 (it passed:
//     two stages, real [OK] responses from grpcbin).
//
//   - FOUND BY RUNNING IT, not by reading docs: ghz PANICS on
//     "--load-start=0" ("LinearPacer.Start cannot be 0"), which is exactly
//     what torture.yaml's first ramp stage declares (a ramp from rest).
//     The emitted script substitutes 1 rps and says so inline; without the
//     live run this emitter would have shipped a script that crashes on
//     its own first command.
//
//   - NOT VERIFIED: nothing here was run against a real application's own
//     gRPC service, because torture.yaml names none (see below). TLS
//     ("--cert"/"--cacert") was never exercised — only plaintext with
//     --insecure. ghz's streaming-RPC behaviour was not exercised: grpcbin's
//     Index is unary.
//
// What this emitter refuses to invent. torture.yaml (R-CFG-3) carries an
// HTTP base_url, and nothing else about a gRPC endpoint: no gRPC address,
// no .proto path, no fully-qualified method, no request payload. Assuming
// the gRPC server shares base_url's port is exactly the kind of guess that
// produces a confident, wrong run, so all four are required environment
// variables the emitted script refuses to run without (TORTUREU_GRPC_ADDR,
// TORTUREU_CALL, TORTUREU_PROTO — which may be empty when the server has
// reflection enabled — and TORTUREU_DATA, defaulting to the empty message
// {}). This mirrors sysbench's CHANGE_ME credentials in protocol.go: a
// placeholder that fails loudly beats a default that runs against the
// wrong thing.
//
// What it does NOT translate, and says so per item: every fault (ghz is a
// load generator; it injects nothing — use "tortureu emit pumba", "netem"
// or "iptables"), and every load.scenarios entry (an HTTP method/path flow
// is not a gRPC method call; ghz drives one method per invocation).
package emit

import (
	"fmt"
	"math"
	"strings"

	"github.com/jd316/TortureU/internal/config"
	"github.com/jd316/TortureU/internal/detect"
)

const ghzHeader = `#!/usr/bin/env bash
# Generated by tortureu emit ghz. Requires: ghz on PATH (https://ghz.sh),
# or the ghcr.io/bojand/ghz image.
#
# torture.yaml describes an HTTP target (target.base_url) and says nothing
# about a gRPC endpoint, so the four things ghz cannot run without are
# REQUIRED environment variables rather than guesses:
#
#   TORTUREU_GRPC_ADDR       host:port of the gRPC server. NOT derived from
#                            target.base_url: that is an HTTP address, and
#                            assuming gRPC shares its port would be a guess.
#   TORTUREU_CALL            fully-qualified method, e.g. pkg.Service/Method
#   TORTUREU_PROTO           path to the .proto file. May be set EMPTY when
#                            the server has gRPC server reflection enabled —
#                            ghz then discovers the schema itself.
#   TORTUREU_DATA            request JSON (default: the empty message {})
#   TORTUREU_GHZ_EXTRA_ARGS  extra ghz flags; add --insecure for a plaintext
#                            (non-TLS) server, --cacert/--cert for TLS.
#
# VERIFICATION STATUS: every flag combination below was run for real on the
# implementer's machine by the real ghz binary (ghcr.io/bojand/ghz:latest)
# against a live gRPC server (moul/grpcbin): constant rate (--rps/--duration),
# the ramp schedule (--load-schedule=line with --load-start/--load-end/
# --load-step/--load-step-duration), a descending ramp with a negative
# --load-step, and a --proto/--call invocation against a real .proto file.
# NOT verified: TLS flags, streaming RPCs, and any real application's own
# service — see grpc.go's header for the full statement.
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml). Run each stage
# yourself in the order given; ghz has no k6 clock to anchor to (R-EXE-8).
`

// ghzPreamble is the shell that turns the four unknowable values into
// required inputs. "${VAR:?message}" aborts the script with that message
// when VAR is unset or empty, so an unconfigured script cannot silently
// run against the wrong endpoint.
const ghzPreamble = `
set -euo pipefail

ADDR="${TORTUREU_GRPC_ADDR:?set TORTUREU_GRPC_ADDR to the gRPC host:port; torture.yaml does not carry one}"
CALL="${TORTUREU_CALL:?set TORTUREU_CALL to the fully-qualified method, e.g. pkg.Service/Method}"
# ? without a colon: an EMPTY TORTUREU_PROTO is allowed (server reflection),
# an UNSET one is not — the difference must be a deliberate choice.
PROTO="${TORTUREU_PROTO?set TORTUREU_PROTO to the .proto path, or to the empty string if the server has reflection enabled}"
DATA="${TORTUREU_DATA:-}"
if [ -z "$DATA" ]; then DATA='{}'; fi

PROTO_ARGS=()
if [ -n "$PROTO" ]; then PROTO_ARGS=(--proto "$PROTO"); fi
read -r -a EXTRA_ARGS <<< "${TORTUREU_GHZ_EXTRA_ARGS:-}"
`

// grpcNoProtoNote refuses, and says which of the two different reasons
// applies. A nil *detect.System means detection never ran — reporting that
// as "this repo has no .proto files" would blame the repo for our own
// missing input (the same distinction protocol.go's noDepNote draws).
func grpcNoProtoNote(sys *detect.System) string {
	if sys == nil {
		return "# tortureu emit ghz: the system could not be detected, so whether this repo\n" +
			"# defines any gRPC service (registry.yaml gates ghz on spec:proto) is unknown;\n" +
			"# nothing to emit. Re-run where detection can read the compose file.\n"
	}
	return "# tortureu emit ghz: no .proto file was detected (spec:proto is false), and ghz\n" +
		"# drives gRPC only; nothing to emit.\n"
}

// Ghz translates torture.yaml's load: block into one ghz invocation per
// load.stages phase: a hold: stage is ghz's constant schedule (--rps), and
// a to:/over: ramp is its "line" schedule, whose --load-step is the rate
// change per --load-step-duration. Every fault and every scenario is
// reported as untranslated rather than dropped (R-CLI-8).
func Ghz(cfg *config.Config, sys *detect.System) (string, error) {
	if sys == nil || !sys.Coverage.Proto {
		return grpcNoProtoNote(sys), nil
	}

	steps, err := buildSteps(cfg)
	if err != nil {
		return "", fmt.Errorf("emit ghz: %w", err)
	}
	faultsOut, err := checkFaults("ghz", cfg)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(ghzHeader)
	b.WriteString(ghzPreamble)

	if len(steps) == 0 {
		b.WriteString("\n# no load.stages declared in torture.yaml: no ghz invocation to emit.\n")
	}
	for _, st := range steps {
		b.WriteString("\n")
		fmt.Fprintf(&b, "# phase %q: %s\n", st.phase, ghzStageDescription(st))
		flags, note := ghzStageFlags(st)
		if note != "" {
			b.WriteString(note)
		}
		if flags == "" {
			continue
		}
		fmt.Fprintf(&b, "ghz \"${PROTO_ARGS[@]}\" \"${EXTRA_ARGS[@]}\" --call \"$CALL\" -d \"$DATA\" %s \"$ADDR\"\n", flags)
	}

	if len(cfg.Load.Scenarios) > 0 {
		b.WriteString("\n# load.scenarios declared in torture.yaml. ghz drives ONE gRPC method per\n" +
			"# invocation (TORTUREU_CALL above) and an HTTP method/path flow is not a gRPC\n" +
			"# call, so none of these is translated — they are listed, not dropped:\n")
		for _, sc := range cfg.Load.Scenarios {
			fmt.Fprintf(&b, "#   scenario %q (weight %d, %d HTTP step(s)): not translated by ghz — "+
				"run one ghz per gRPC method instead, or use \"tortureu run\" for the HTTP flow.\n",
				sc.Name, sc.Weight, len(sc.Flow))
		}
	}

	if faultsOut != "" {
		b.WriteString("\n# faults declared in torture.yaml's faults: block (a load generator injects\n" +
			"# nothing; use tortureu emit pumba/netem/iptables instead):\n")
		b.WriteString(faultsOut)
	}
	return b.String(), nil
}

// ghzStageDescription renders the stage a human is looking at, in
// torture.yaml's own terms, so the emitted flags can be checked against
// what was declared.
func ghzStageDescription(st loadStep) string {
	if st.ramp && st.from != st.to {
		return fmt.Sprintf("%s -> %s rps over %ss", fmtNum(st.from), fmtNum(st.to), fmtNum(st.secs))
	}
	return fmt.Sprintf("hold %s rps for %ss", fmtNum(st.to), fmtNum(st.secs))
}

// ghzStageFlags renders one stage's ghz load-schedule flags, plus any note
// the translation owes the reader. flags is "" when the stage cannot be
// expressed at all — reported, never silently rounded away.
func ghzStageFlags(st loadStep) (flags, note string) {
	duration := fmtNum(st.secs) + "s"
	if !st.ramp || st.from == st.to {
		return fmt.Sprintf("--rps=%s --duration=%s", fmtNum(st.to), duration), ""
	}

	// ghz's line schedule adds --load-step to the current rate every
	// --load-step-duration. A 1s step duration keeps the emitted slope
	// directly comparable to torture.yaml's "N rps over Ds".
	slope := (st.to - st.from) / st.secs
	step := math.Round(slope)
	if step == 0 {
		return "", fmt.Sprintf("# NOT TRANSLATED: this ramp changes the rate by %s rps/s, and ghz's\n"+
			"# --load-step is an integer number of rps per step — it cannot express a\n"+
			"# slope this shallow. Split the phase into longer steps, or drive it with\n"+
			"# \"tortureu run\" (k6's ramping-arrival-rate takes fractional rates).\n",
			fmtNum(slope))
	}
	// A ramp from rest declares a start rate of 0, which the real ghz
	// binary does not accept: its linear pacer panics with
	// "LinearPacer.Start cannot be 0" (observed, not inferred — see this
	// file's VERIFICATION STATUS). 1 rps is the nearest rate it will run,
	// and the substitution is disclosed rather than applied quietly.
	start := st.from
	if start < 1 {
		start = 1
		note += "# note: the declared start rate is 0 rps, and ghz panics on one (\"LinearPacer.Start\n" +
			"# cannot be 0\"); --load-start=1 is used instead. The first second of this ramp\n" +
			"# therefore offers 1 rps more than declared.\n"
	}
	if step != slope {
		note += fmt.Sprintf("# note: the declared slope is %s rps/s, rounded to %s (ghz's --load-step is\n"+
			"# an integer); the ramp therefore reaches --load-end early or late by up to\n"+
			"# one step rather than tracking the declared rate exactly.\n",
			fmtNum(slope), fmtNum(step))
	}
	return fmt.Sprintf("--load-schedule=line --load-start=%s --load-end=%s --load-step=%s --load-step-duration=1s --duration=%s",
		fmtNum(start), fmtNum(st.to), fmtNum(step), duration), note
}

func init() {
	// needsSystem: registry.yaml gates ghz on spec:proto, which is a
	// detection fact (Coverage.Proto), not a torture.yaml one.
	Register("ghz", Ghz, true)
}
