package emit

import (
	"fmt"
	"strings"

	"github.com/jdb316/tortureu/internal/config"
	"github.com/jdb316/tortureu/internal/fault"
)

// iptablesHeader documents this tool's one job: connection-refused
// (`down:`) faults, from the SUT's own point of view. iptables can also do
// latency/bandwidth shaping (via tc's own filters, or ipset+netem
// combinations) but this emit does not attempt that — "tortureu emit
// netem" already owns network-shaping faults, and duplicating the same
// verb across two tools with two different confidence levels would be
// worse than one tool that is honest about its scope.
const iptablesHeader = `#!/usr/bin/env bash
# Generated by tortureu emit iptables. Requires: docker, and iptables
# installed inside the SUT container, plus NET_ADMIN on it.
#
# This tool only translates the "down" verb — a dependency becoming
# unreachable. It runs the rule inside the SUT's own container (target ==
# egress direction) so the SUT experiences the dependency as gone, which
# is the same client-visible effect Toxiproxy's "down" produces (an
# immediately refused connection, not a silent drop).
#
# Every "down" fault below is emitted as REJECT --reject-with tcp-reset
# (refused, matches Toxiproxy's own semantics) with the DROP (blackhole,
# silent-timeout) alternative alongside it as a comment, since the
# registry itself flags these as materially different client behaviours
# and torture.yaml's "down: true" cannot express which one you mean.
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml). Run each block
# yourself when the fault's "at:" phase begins.
`

// IPTables translates `down` faults into iptables REJECT rules (R-CLI-8
// proposed). Every other verb is reported with a skipComment naming why.
func IPTables(cfg *config.Config) (string, error) {
	var b strings.Builder
	b.WriteString(iptablesHeader)
	found := false
	for _, f := range cfg.Faults {
		act, err := fault.Translate(f)
		if err != nil {
			return "", fmt.Errorf("emit iptables: %w", err)
		}
		if act.Kind != fault.KindToxic || !act.Toxic.Disable {
			b.WriteString("\n" + atComment(f))
			b.WriteString(skipComment("iptables", f, iptablesReason(act)))
			continue
		}
		found = true
		b.WriteString("\n" + atComment(f))
		b.WriteString(iptablesCommand(cfg, f))
	}
	if !found {
		b.WriteString("\n# no down: faults found in torture.yaml's faults: block.\n")
	}
	return b.String(), nil
}

func iptablesReason(act fault.Action) string {
	switch {
	case act.Kind == fault.KindPassed:
		return fmt.Sprintf("owned by %s, not a connectivity fault", act.Owner)
	case act.Kind == fault.KindDocker:
		return "a container-level fault (signal/stress), not a connectivity fault; see \"tortureu emit pumba\""
	case act.Kind == fault.KindToxic:
		return fmt.Sprintf("only \"down\" is translated; tc netem shaping faults belong to \"tortureu emit netem\", and iptables has no verified equivalent of Toxiproxy's %q toxic", act.Toxic.Type)
	default:
		return "unrecognized action"
	}
}

// iptablesCommand renders the add/teardown pair for one down fault,
// against target's egress from the SUT container, plus the commented-out
// DROP alternative.
func iptablesCommand(cfg *config.Config, f config.Fault) string {
	var chain, match string
	if f.Target == cfg.Target.Service {
		// The SUT refusing its own connections: filter on the SUT's own
		// listening port (from target.base_url) rather than a peer.
		port := basePort(cfg.Target.BaseURL)
		chain = "INPUT"
		if port != "" {
			match = fmt.Sprintf("-p tcp --dport %s", port)
		}
	} else {
		host, port := hostPort(f.Target)
		chain = "OUTPUT"
		match = fmt.Sprintf("-p tcp -d %s", host)
		if port != "" {
			match += " --dport " + port
		}
	}

	container := cfg.Target.Service
	var b strings.Builder
	fmt.Fprintf(&b, "docker exec %s iptables -A %s %s -j REJECT --reject-with tcp-reset\n", container, chain, match)
	b.WriteString("# blackhole alternative (silent drop, causes a client-side timeout instead of a refused connection):\n")
	fmt.Fprintf(&b, "# docker exec %s iptables -A %s %s -j DROP\n", container, chain, match)
	if f.For != "" {
		fmt.Fprintf(&b, "sleep %s && docker exec %s iptables -D %s %s -j REJECT --reject-with tcp-reset\n", f.For, container, chain, match)
	} else {
		fmt.Fprintf(&b, "# no for: duration given; remove manually: docker exec %s iptables -D %s %s -j REJECT --reject-with tcp-reset\n", container, chain, match)
	}
	return b.String()
}
