// xk6-kafka — Kafka producer load, emitted as a k6 script (R-CLI-8
// proposed; registry.yaml: tier delegate, when: dep:kafka, how:
// "tortureu emit kafka-load").
//
// VERIFICATION STATUS (what was actually run, and what was not):
//
//   - VERIFIED for real, on this machine: the exact script shape this file
//     emits — the k6/x/kafka imports, the SchemaRegistry.serialize()
//     message construction, the Writer constructor, and the
//     ramping-arrival-rate scenario built from load.stages — was executed
//     by a real k6 binary with the real extension
//     (mostafamoradian/xk6-kafka:latest, k6 v1.7.1 with
//     github.com/mostafa/xk6-kafka/v2) against a real broker
//     (redpandadata/redpanda:v24.2.7, joined via --network container:).
//     It produced 179 messages over a two-stage 6s profile with
//     kafka_writer_error_count 0. The poison-pill and duplicate injector
//     scenarios were run the same way, as their own k6 invocations.
//
//   - NOT VERIFIED: no consumer was attached, so what a poison pill does
//     to a real consumer group (RESEARCH.md §18's "one malformed message
//     blocks an entire partition") was NOT observed here — this emit
//     produces the malformed message, and what it costs is your
//     consumer's property, not ours. Nothing was run against Confluent
//     Cloud, a schema registry, SASL/TLS auth, or a partitioned
//     multi-broker cluster.
//
// What this emitter refuses to invent: the broker address comes from
// detection (R-DET-4) and nothing else — with no kafka dependency
// detected it refuses, exactly as sysbench/memtier do. The LOAD topic is
// not in torture.yaml's schema at all, so it is a required KAFKA_TOPIC
// environment variable the script throws without: producing into a guessed
// topic is a real, irreversible write to someone's broker. Credentials are
// never emitted; a cluster needing SASL/TLS needs the Writer options
// edited, and the emitted header says so.
//
// What it DOES translate, via internal/queuefault (never re-derived):
// poison_pill and duplicate, the two verbs R-EXE-15 assigns to the broker
// producer, each using the fault's own target as its topic (that is what
// queuefault.Translate returns). Every other verb is reported per fault as
// untranslated — a Kafka producer cannot add latency to a broker or kill a
// container.
//
// Scheduling: none (R-CLI-8, delegate tier). The injector scenarios are
// selected by TORTUREU_SCENARIO at k6 launch time, so the operator starts
// each one when its fault's at: window begins; no start time is derived
// from the phase clock.
package emit

import (
	"fmt"
	"strings"

	"github.com/jd316/TortureU/internal/config"
	"github.com/jd316/TortureU/internal/detect"
	"github.com/jd316/TortureU/internal/fault"
	"github.com/jd316/TortureU/internal/queuefault"
)

const kafkaHeader = `// Generated by tortureu emit kafka-load. Requires: a k6 binary built with
// the xk6-kafka extension (https://github.com/mostafa/xk6-kafka), e.g.
// "docker run --rm -i mostafamoradian/xk6-kafka run -" or your own
// "xk6 build --with github.com/mostafa/xk6-kafka".
//
// Run the load profile:      k6 run -e KAFKA_TOPIC=<topic> this-script.js
// Run one fault injector:    k6 run -e TORTUREU_SCENARIO=<fault name> this-script.js
//
// KAFKA_TOPIC is REQUIRED and has no default: torture.yaml has no topic
// field, and producing into a guessed topic is a real write to a real log
// that cannot be taken back. Fault injectors use their fault's own target
// as the topic (that is what internal/queuefault reads it as).
//
// No SASL/TLS credentials are emitted — torture.yaml carries none. Add
// them to the Writer options below if your cluster needs them.
//
// VERIFICATION STATUS: this script shape was executed by a real k6 +
// xk6-kafka build (mostafamoradian/xk6-kafka, k6 v1.7.1) against a real
// broker (redpanda v24.2.7) and produced real messages with zero writer
// errors. NOT verified: consumer-side effects of a poison pill, schema
// registry / Avro payloads, SASL/TLS, and multi-broker partitioning.
//
// at:/for: are NOT scheduled by this script — this is a delegate-tier
// handoff (real output, separate timing, registry.yaml). Launch each
// injector yourself when its fault's at: phase begins.
`

// kafkaQueueFault is one translated poison_pill/duplicate fault, carrying
// the queuefault action and the JS identifier its scenario/function use.
type kafkaQueueFault struct {
	fault  config.Fault
	action queuefault.Action
	ident  string
}

// KafkaLoad emits a k6 script driving the detected Kafka broker: an open
// arrival-rate producer profile from load.stages (R-CFG-6) plus one
// injector scenario per poison_pill/duplicate fault, translated through
// internal/queuefault. Every other fault is reported as untranslated
// rather than dropped (R-CLI-8).
func KafkaLoad(cfg *config.Config, sys *detect.System) (string, error) {
	dep, ok := findDep(sys, "kafka")
	if !ok {
		return noDepNote("kafka-load", sys, "kafka"), nil
	}
	broker := dep.Address
	if broker == "" {
		// Detection found the dependency but not an address (R-DET-4
		// could not derive host:port). Refuse rather than assume 9092 on
		// the service name — a producer pointed at the wrong port fails
		// in a way that looks like a broken broker.
		return fmt.Sprintf("# tortureu emit kafka-load: the kafka dependency %q was detected but no\n"+
			"# host:port could be derived for it (R-DET-4), and a broker address must not be\n"+
			"# guessed; nothing to emit.\n", dep.Name), nil
	}

	steps, err := buildSteps(cfg)
	if err != nil {
		return "", fmt.Errorf("emit kafka-load: %w", err)
	}

	var queueFaults []kafkaQueueFault
	var skipped strings.Builder
	for _, f := range cfg.Faults {
		act, terr := fault.Translate(f)
		if terr != nil {
			return "", fmt.Errorf("emit kafka-load: %w", terr)
		}
		// R-EXE-15: internal/fault passes poison_pill and duplicate over
		// to internal/queuefault, which is this emitter's own layer.
		if act.Kind == fault.KindPassed && act.Owner == "internal/queuefault" {
			qact, qerr := queuefault.Translate(f)
			if qerr != nil {
				return "", fmt.Errorf("emit kafka-load: %w", qerr)
			}
			queueFaults = append(queueFaults, kafkaQueueFault{fault: f, action: qact, ident: ident(f.Name)})
			continue
		}
		reason := "a Kafka producer injects messages, not network or container faults; " +
			"use \"tortureu emit pumba\", \"netem\" or \"iptables\""
		if act.Kind == fault.KindPassed {
			reason = fmt.Sprintf("owned by %s, not the broker producer", act.Owner)
		}
		skipped.WriteString(kafkaComment(atComment(f)))
		skipped.WriteString(kafkaComment(skipComment("kafka-load", f, reason)))
	}

	vus := 10
	if rps, has := peakRPS(cfg.Load); has {
		vus = concurrencyFromRPS(rps)
	}

	var b strings.Builder
	b.WriteString(kafkaHeader)
	fmt.Fprintf(&b, `
import { Writer, SchemaRegistry, SCHEMA_TYPE_STRING } from "k6/x/kafka";

// Broker address from detection (R-DET-4), not a default.
const brokers = [%q];
const schemaRegistry = new SchemaRegistry();

// Which scenario this k6 invocation runs. Unset runs the load profile;
// a fault name runs that injector. Nothing here is scheduled against the
// load phase clock — that timing is yours (delegate tier).
const selected = __ENV.TORTUREU_SCENARIO || "load";
const loadTopic = __ENV.KAFKA_TOPIC;
if (selected === "load" && !loadTopic) {
  throw new Error("KAFKA_TOPIC is required: torture.yaml carries no topic, and tortureu will not guess one");
}
`, broker)

	b.WriteString(`
function message(key, value) {
  return {
    key: schemaRegistry.serialize({ data: key, schemaType: SCHEMA_TYPE_STRING }),
    value: schemaRegistry.serialize({ data: value, schemaType: SCHEMA_TYPE_STRING }),
  };
}

const scenarios = {};
`)

	if len(steps) == 0 {
		b.WriteString("\n// no load.stages declared in torture.yaml: no load scenario emitted.\n")
	} else {
		b.WriteString("\n// load.stages (R-CFG-6's open arrival-rate model) -> k6's own open-model\n" +
			"// executor. One produced message per arrival, so the offered rate does not\n" +
			"// self-throttle when the broker slows down.\n")
		b.WriteString("if (selected === \"load\") {\n  scenarios.kafka_load = {\n" +
			"    executor: 'ramping-arrival-rate',\n    startRate: 0,\n    timeUnit: '1s',\n")
		fmt.Fprintf(&b, "    preAllocatedVUs: %d,\n    maxVUs: %d,\n", vus, vus*4)
		b.WriteString("    exec: 'produceLoad',\n    stages: [\n")
		for _, st := range steps {
			fmt.Fprintf(&b, "      { target: %s, duration: '%ss' }, // phase %q\n", fmtNum(st.to), fmtNum(st.secs), st.phase)
		}
		b.WriteString("    ],\n  };\n}\n")
	}

	for _, qf := range queueFaults {
		b.WriteString("\n" + kafkaComment(atComment(qf.fault)))
		switch qf.action.Kind {
		case queuefault.KindPoisonPill:
			p := qf.action.PoisonPill
			fmt.Fprintf(&b, "// fault %q: %d malformed message(s) onto topic %q (internal/queuefault).\n",
				qf.fault.Name, p.Count, p.Topic)
			fmt.Fprintf(&b, "if (selected === %q) {\n  scenarios.%s = {\n    executor: 'shared-iterations',\n"+
				"    vus: 1,\n    iterations: %d,\n    exec: 'poisonPill_%s',\n  };\n}\n",
				qf.fault.Name, qf.ident, p.Count, qf.ident)
		case queuefault.KindDuplicate:
			d := qf.action.Duplicate
			fmt.Fprintf(&b, "// fault %q: re-produce %v of messages onto topic %q (internal/queuefault).\n",
				qf.fault.Name, d.Rate, d.Topic)
			dur := qf.fault.For
			if dur == "" {
				dur = "30s"
				b.WriteString("// no for: duration declared; this injector runs 30s. Edit it — nothing\n" +
					"// here reads the load phase clock.\n")
			}
			if rate, has := peakRPS(cfg.Load); has {
				b.WriteString("// Paced at load.stages' peak rate so the injector offers the same\n" +
					"// intensity the load profile does, rather than producing as fast as the\n" +
					"// broker will accept (an unpaced VU loop is a firehose, not a fault:\n" +
					"// measured at ~14,600 iterations/s against a local broker).\n")
				fmt.Fprintf(&b, "if (selected === %q) {\n  scenarios.%s = {\n    executor: 'constant-arrival-rate',\n"+
					"    rate: %d,\n    timeUnit: '1s',\n    duration: '%s',\n    preAllocatedVUs: %d,\n    maxVUs: %d,\n"+
					"    exec: 'duplicate_%s',\n  };\n}\n",
					qf.fault.Name, qf.ident, rate, dur, vus, vus*4, qf.ident)
			} else {
				b.WriteString("// WARNING: torture.yaml declares no load.stages rate, so there is nothing\n" +
					"// to pace this injector against. A single VU looping unthrottled produces as\n" +
					"// fast as the broker accepts (~14,600/s against a local broker when measured)\n" +
					"// — set an explicit rate before running this against anything you care about.\n")
				fmt.Fprintf(&b, "if (selected === %q) {\n  scenarios.%s = {\n    executor: 'constant-vus',\n"+
					"    vus: 1,\n    duration: '%s',\n    exec: 'duplicate_%s',\n  };\n}\n",
					qf.fault.Name, qf.ident, dur, qf.ident)
			}
		}
	}

	b.WriteString("\nexport const options = { scenarios: scenarios };\n")

	if len(steps) > 0 {
		b.WriteString(`
const loadWriter = loadTopic ? new Writer({ brokers: brokers, topic: loadTopic, autoCreateTopic: true }) : null;

export function produceLoad() {
  loadWriter.produce({ messages: [message(` + "`tortureu-${__VU}-${__ITER}`" + `, JSON.stringify({ vu: __VU, iter: __ITER, ts: Date.now() }))] });
}
`)
	}

	for _, qf := range queueFaults {
		switch qf.action.Kind {
		case queuefault.KindPoisonPill:
			p := qf.action.PoisonPill
			fmt.Fprintf(&b, "\nconst writer_%s = new Writer({ brokers: brokers, topic: %q, autoCreateTopic: true });\n", qf.ident, p.Topic)
			b.WriteString("// \"Malformed\" is consumer-specific: this writes a payload that is neither\n" +
				"// valid JSON nor a valid Avro/protobuf record. If your consumer would accept\n" +
				"// it, edit the value below — a poison pill your consumer can parse is not one.\n")
			fmt.Fprintf(&b, "export function poisonPill_%s() {\n"+
				"  writer_%s.produce({ messages: [message(`tortureu-poison-${__ITER}`, '{\\x00 NOT-VALID-JSON tortureu poison_pill ' + __ITER)] });\n}\n",
				qf.ident, qf.ident)
		case queuefault.KindDuplicate:
			d := qf.action.Duplicate
			fmt.Fprintf(&b, "\nconst writer_%s = new Writer({ brokers: brokers, topic: %q, autoCreateTopic: true });\n", qf.ident, d.Topic)
			b.WriteString("// LIMIT, stated rather than hidden: this is a PRODUCER-side duplicate — it\n" +
				"// produces its own message and, at the declared rate, produces it a second\n" +
				"// time with the same key. It cannot re-deliver a message your application\n" +
				"// already produced or a consumer already read; that needs a consumer-side\n" +
				"// redelivery loop, which a k6 producer script cannot provide.\n")
			fmt.Fprintf(&b, "export function duplicate_%s() {\n"+
				"  const m = message(`tortureu-dup-${__VU}-${__ITER}`, JSON.stringify({ vu: __VU, iter: __ITER }));\n"+
				"  writer_%s.produce({ messages: [m] });\n"+
				"  if (Math.random() < %v) {\n    writer_%s.produce({ messages: [m] }); // the duplicate\n  }\n}\n",
				qf.ident, qf.ident, d.Rate, qf.ident)
		}
	}

	if skipped.Len() > 0 {
		b.WriteString("\n// faults declared in torture.yaml that this emit does NOT translate\n" +
			"// (listed, never dropped — R-CLI-8):\n")
		b.WriteString(skipped.String())
	}
	return b.String(), nil
}

// kafkaComment converts one shared "# ..." comment line (common.go's
// atComment/skipComment, written for the bash emitters) into a JavaScript
// line comment, since "#" is not a comment token in JS.
func kafkaComment(line string) string {
	var out strings.Builder
	for _, l := range strings.Split(strings.TrimRight(line, "\n"), "\n") {
		out.WriteString("// " + strings.TrimPrefix(l, "# ") + "\n")
	}
	return out.String()
}

func init() {
	// needsSystem: the broker address is a detection fact (R-DET-4), and
	// this emitter refuses rather than guessing one.
	Register("kafka-load", KafkaLoad, true)
}
