// Dependency-virtualization emits (registry.yaml domain 9, R-CLI-8
// proposed): `tortureu emit hoverfly` and `tortureu emit localstack`.
//
// Neither tool is a fault injector, and this file refuses to pretend
// otherwise. Hoverfly stands in for a `class: mock` egress host and can
// carry exactly one fault verb as a response behaviour (latency, via the
// simulation's globalActions.delays). LocalStack emulates the AWS API and
// carries none at all. Every other fault in torture.yaml is reported, per
// fault, as untranslated with the reason — never dropped (R-CLI-8) — and
// the reports name the emitter that DOES translate it.
//
// Nothing here guesses an address, region, credential or response body.
// torture.yaml carries no response bodies and no AWS region, so the
// hoverfly simulation answers with an empty body and the localstack script
// fails closed on an unset AWS_REGION, in the manner protocol.go's
// noDepNote established for sysbench/memtier.
//
// VERIFICATION STATUS (performed on this host, 2026-08-08, with Docker):
//
//	VERIFIED — hoverfly: this emitter's output was written to a file and
//	  run verbatim with bash. It started spectolabs/hoverfly:v1.12.11,
//	  waited on the admin API, and imported the simulation it generated
//	  (schemaVersion v5.3, one destination-matched pair, one
//	  globalActions.delays entry with an escaped urlPattern) via
//	  `PUT /api/v2/simulation`. A request through the proxy to the mocked
//	  host then returned 200 after 2.010s — the 2000ms delay this file
//	  derives from `inject: {latency: 2s}` really applied — and a request
//	  to a host absent from the simulation returned 502.
//	VERIFIED — localstack: this emitter's output was likewise run verbatim.
//	  With AWS_REGION unset it exits non-zero with the message above and
//	  starts nothing; with AWS_REGION=eu-west-1 it started
//	  localstack/localstack:4.0, and /_localstack/health then reported
//	  exactly the one detected service ("s3": "available") with every other
//	  service "disabled", the container carrying SERVICES=s3 and
//	  AWS_DEFAULT_REGION=eu-west-1. In a separate run of the same image a
//	  real S3 bucket was created and listed through the emitted endpoint.
//	  Also verified NEGATIVELY: localstack/localstack:latest (2026.7.2)
//	  exits with code 55, "License activation failed", without a
//	  LOCALSTACK_AUTH_TOKEN — which is why the emitted script pins :4.0.
//	NOT VERIFIED — neither tool was wired to a real system under test: no
//	  compose stack was pointed at the hoverfly proxy or the localstack
//	  endpoint, so the HTTP_PROXY / AWS_ENDPOINT_URL wiring the emitted
//	  comments describe is documentation, not a tested claim.
//	NOT VERIFIED — LocalStack's Chaos API (its Pro-only fault injection).
//	  No licence was available, so this file claims nothing about it and
//	  translates no fault into it.
package emit

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/jdb316/tortureu/internal/config"
	"github.com/jdb316/tortureu/internal/detect"
	"github.com/jdb316/tortureu/internal/fault"
)

// hoverflySimHeredoc delimits the simulation JSON inside the emitted
// script. Named (not inlined) because this package's tests parse the
// simulation back out of the script by this marker.
const hoverflySimHeredoc = "HOVERFLY_SIMULATION"

// hoverflyImage is the exact image this file's verification ran against.
// Pinned rather than :latest so the emitted script and the verification
// claim above cannot drift apart.
const hoverflyImage = "spectolabs/hoverfly:v1.12.11"

// hoverflySchemaVersion is the simulation schema hoverfly v1.12.11 itself
// reports when it exports what it accepted (it normalised the v5.2
// document used during verification to v5.3).
const hoverflySchemaVersion = "v5.3"

const hoverflyHeader = `#!/usr/bin/env bash
# Generated by tortureu emit hoverfly. Requires: docker, curl.
#
# Hoverfly is HTTP service virtualization: it stands in for the hosts
# torture.yaml classifies "class: mock" (R-CFG-4/R-CFG-5), so the run never
# reaches the real vendor. It is NOT a fault injector. The only fault verb
# it carries here is latency, as a simulation response delay; every other
# fault is reported below as untranslated, with the emitter that does
# translate it named.
#
# WHAT THIS SIMULATION DOES NOT CONTAIN: no response bodies. torture.yaml
# records which hosts are mocked and from what (spec|capture), never what
# they should answer, so each pair below returns 200 with an EMPTY body.
# Fill the bodies in (or import a capture/spec-derived simulation instead)
# before pointing a real SUT at this — an invented payload would be worse
# than an empty one.
#
# Any host NOT in the simulation gets a 502 from hoverfly (verified), which
# is the same default-deny posture as egress.default: deny (R-DC2-1) — but
# hoverfly is a proxy, not the network isolation R-DC2-3 requires. It does
# not enforce the egress boundary; it only answers what is routed to it.
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml).
set -euo pipefail
`

const hoverflyNoMockHostsNote = `# tortureu emit hoverfly: no egress host in torture.yaml is classified
# "class: mock", so there is no virtualized dependency to build a simulation
# for; nothing to emit. Classify a host with "class: mock" and "from:
# spec|capture" (R-CFG-5) if you want hoverfly to stand in for it.
`

// --- hoverfly simulation schema (v5.x) -------------------------------------
//
// Modeled as structs and marshaled rather than string-templated, so this
// package's tests can parse back exactly what is emitted (the standard
// platform.go's header sets for the same reason).

type hoverflyMatcher struct {
	Matcher string `json:"matcher"`
	Value   string `json:"value"`
}

type hoverflyRequest struct {
	Destination []hoverflyMatcher `json:"destination"`
	Path        []hoverflyMatcher `json:"path"`
}

type hoverflyResponse struct {
	Status      int                 `json:"status"`
	Body        string              `json:"body"`
	EncodedBody bool                `json:"encodedBody"`
	Templated   bool                `json:"templated"`
	Headers     map[string][]string `json:"headers"`
}

type hoverflyPair struct {
	Request  hoverflyRequest  `json:"request"`
	Response hoverflyResponse `json:"response"`
}

type hoverflyDelay struct {
	URLPattern string `json:"urlPattern"`
	HTTPMethod string `json:"httpMethod"`
	Delay      int    `json:"delay"`
}

type hoverflyGlobalActions struct {
	Delays []hoverflyDelay `json:"delays"`
}

type hoverflyData struct {
	Pairs         []hoverflyPair        `json:"pairs"`
	GlobalActions hoverflyGlobalActions `json:"globalActions"`
}

type hoverflyMeta struct {
	SchemaVersion string `json:"schemaVersion"`
}

type hoverflySimulation struct {
	Data hoverflyData `json:"data"`
	Meta hoverflyMeta `json:"meta"`
}

// hoverflyMockHosts returns the egress hosts classified "class: mock",
// sorted so the emitted simulation is stable.
func hoverflyMockHosts(cfg *config.Config) []string {
	var hosts []string
	for host, eh := range cfg.Egress.Hosts {
		if eh.Class == "mock" {
			hosts = append(hosts, host)
		}
	}
	sort.Strings(hosts)
	return hosts
}

// Hoverfly translates torture.yaml's mocked egress hosts into a hoverfly
// simulation, plus the commands to run and import it (R-CLI-8 proposed).
// Fault semantics come from internal/fault.Translate — never re-derived
// here — and every fault this tool cannot carry is reported.
func Hoverfly(cfg *config.Config) (string, error) {
	hosts := hoverflyMockHosts(cfg)
	mocked := make(map[string]bool, len(hosts))
	for _, h := range hosts {
		mocked[h] = true
	}

	var b strings.Builder
	b.WriteString(hoverflyHeader)
	b.WriteString("\n# ---- fault coverage ------------------------------------------------\n")

	var delays []hoverflyDelay
	for _, f := range cfg.Faults {
		act, err := fault.Translate(f)
		if err != nil {
			return "", fmt.Errorf("emit hoverfly: %w", err)
		}
		b.WriteString(atComment(f))
		delay, note, reason, ok := hoverflyFaultDelay(f, act, mocked)
		if !ok {
			b.WriteString(skipComment("hoverfly", f, reason))
			continue
		}
		delays = append(delays, delay)
		fmt.Fprintf(&b, "# fault %q: latency %dms -> globalActions.delays urlPattern %s\n", f.Name, delay.Delay, delay.URLPattern)
		if note != "" {
			fmt.Fprintf(&b, "# fault %q: %s\n", f.Name, note)
		}
	}
	if len(cfg.Faults) == 0 {
		b.WriteString("# torture.yaml declares no faults: block.\n")
	}

	if len(hosts) == 0 {
		b.WriteString("\n")
		b.WriteString(hoverflyNoMockHostsNote)
		return b.String(), nil
	}

	sim := hoverflySimulation{
		Data: hoverflyData{
			Pairs:         make([]hoverflyPair, 0, len(hosts)),
			GlobalActions: hoverflyGlobalActions{Delays: delays},
		},
		Meta: hoverflyMeta{SchemaVersion: hoverflySchemaVersion},
	}
	if sim.Data.GlobalActions.Delays == nil {
		sim.Data.GlobalActions.Delays = []hoverflyDelay{}
	}
	for _, h := range hosts {
		host, _ := hostPort(h)
		sim.Data.Pairs = append(sim.Data.Pairs, hoverflyPair{
			Request: hoverflyRequest{
				Destination: []hoverflyMatcher{{Matcher: "exact", Value: host}},
				Path:        []hoverflyMatcher{{Matcher: "glob", Value: "*"}},
			},
			Response: hoverflyResponse{Status: 200, Body: "", Headers: map[string][]string{}},
		})
	}
	doc, err := json.MarshalIndent(sim, "", "  ")
	if err != nil {
		return "", fmt.Errorf("emit hoverfly: %w", err)
	}

	fmt.Fprintf(&b, "\n# ---- simulation (%d mocked host(s), schema %s) ----------------------\n",
		len(hosts), hoverflySchemaVersion)
	fmt.Fprintf(&b, "cat > hoverfly-simulation.json <<'%s'\n%s\n%s\n", hoverflySimHeredoc, doc, hoverflySimHeredoc)

	b.WriteString("\n# ---- run and import ------------------------------------------------\n")
	fmt.Fprintf(&b, "docker run -d --name tortureu-hoverfly -p 8500:8500 -p 8888:8888 %s -listen-on-host=0.0.0.0\n", hoverflyImage)
	b.WriteString("until curl -fs http://localhost:8888/api/v2/simulation >/dev/null 2>&1; do sleep 1; done\n")
	b.WriteString("curl -fs -X PUT -H 'Content-Type: application/json' \\\n")
	b.WriteString("  --data @hoverfly-simulation.json http://localhost:8888/api/v2/simulation >/dev/null\n")
	b.WriteString("\n# Point the system under test's HTTP client at the proxy, e.g. in\n")
	fmt.Fprintf(&b, "# %s's environment for %q:\n", cfg.Target.Compose, cfg.Target.Service)
	b.WriteString("#   HTTP_PROXY: http://tortureu-hoverfly:8500\n")
	b.WriteString("#   HTTPS_PROXY: http://tortureu-hoverfly:8500\n")
	b.WriteString("# (and join hoverfly to the same compose network; the host ports above\n")
	b.WriteString("#  are for the import call and for inspecting it from your shell).\n")
	b.WriteString("# Tear down: docker rm -f tortureu-hoverfly\n")
	return b.String(), nil
}

// hoverflyFaultDelay decides whether one fault becomes a simulation delay.
// note carries a modifier that is real in torture.yaml but has no place in
// hoverfly's delay shape (jitter) — reported, never silently dropped.
func hoverflyFaultDelay(f config.Fault, act fault.Action, mocked map[string]bool) (delay hoverflyDelay, note, reason string, ok bool) {
	switch {
	case act.Kind == fault.KindToxic && act.Toxic.Type == "latency":
		if !mocked[f.Target] {
			return hoverflyDelay{}, "", fmt.Sprintf("target %q is not a \"class: mock\" host, so hoverfly is not in its path — use tortureu emit pumba/netem for a network-level delay", f.Target), false
		}
		ms, _ := act.Toxic.Attributes["latency"].(int)
		host, _ := hostPort(f.Target)
		d := hoverflyDelay{URLPattern: regexp.QuoteMeta(host), Delay: ms}
		if jitter, has := act.Toxic.Attributes["jitter"]; has {
			jms, _ := jitter.(int)
			note = fmt.Sprintf("jitter %dms is NOT applied — hoverfly's globalActions.delays takes a fixed delay only "+
				"(its delaysLogNormal alternative takes min/max/mean/median, which this fault does not carry, and was not verified)", jms)
		}
		return d, note, "", true

	case act.Kind == fault.KindToxic && act.Toxic.Disable:
		return hoverflyDelay{}, "", "hoverfly answers requests; it cannot refuse a TCP connection — use tortureu emit iptables or pumba for a refused connection", false

	case act.Kind == fault.KindToxic:
		return hoverflyDelay{}, "", fmt.Sprintf("no verified hoverfly translation of Toxiproxy's %q toxic; hoverfly shapes HTTP responses, not the transport", act.Toxic.Type), false

	case act.Kind == fault.KindDocker:
		return hoverflyDelay{}, "", fmt.Sprintf("%q is a container-level fault against %s, not an HTTP response behaviour — use tortureu emit pumba", act.Docker.Kind, act.Docker.Container), false

	case act.Kind == fault.KindPassed && f.Verb == "error_rate":
		return hoverflyDelay{}, "", "hoverfly's simulation schema has no probabilistic response selection; error_rate is owned by " + act.Owner + " and applied by the drive-tier WireMock path", false

	default:
		return hoverflyDelay{}, "", fmt.Sprintf("owned by %s, not a mocked-HTTP behaviour hoverfly can express", act.Owner), false
	}
}

// --- localstack ------------------------------------------------------------

// localstackImage is the exact image verified on this host. NOT :latest —
// localstack/localstack:latest (2026.7.2) refuses to start without a
// LOCALSTACK_AUTH_TOKEN ("License activation failed", exit code 55), so
// emitting :latest would hand the user a script that cannot run.
const localstackImage = "localstack/localstack:4.0"

// localstackPort is LocalStack's single edge port; every emulated AWS
// service is reached through it.
const localstackPort = "4566"

// localstackServiceTypes are the R-DET-9 dependency types that correspond
// to a LocalStack service, so SERVICES is derived from what detection
// actually found rather than a guessed list.
var localstackServiceTypes = map[string]string{
	"s3":       "s3",
	"sqs":      "sqs",
	"dynamodb": "dynamodb",
}

const localstackHeader = `#!/usr/bin/env bash
# Generated by tortureu emit localstack. Requires: docker, curl.
#
# LocalStack emulates the AWS API so the run never touches a real AWS
# account. It is environment scaffolding, NOT a fault injector: this emit
# translates no fault from torture.yaml into it (LocalStack's Chaos API is
# a Pro feature; no licence was available, so nothing here claims it). Every
# fault is reported below with the emitter that does translate it.
#
# Pinned to ` + localstackImage + ` deliberately: localstack/localstack:latest
# (2026.7.2) exits with code 55, "License activation failed", unless
# LOCALSTACK_AUTH_TOKEN is set — verified on the machine that generated this.
#
# CREDENTIALS: LocalStack accepts any credentials (verified: an S3 bucket was
# created with a dummy signature). The dummy values below are LocalStack's own
# documented convention, not anything read from your repo.
# REGION: torture.yaml carries no AWS region, so this script REFUSES to pick
# one — set AWS_REGION yourself. A guessed region would put every emulated
# resource in the wrong namespace and still look like it worked.
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml).
set -euo pipefail
: "${AWS_REGION:?tortureu emit localstack: torture.yaml carries no AWS region; set AWS_REGION (e.g. AWS_REGION=eu-west-1 ./this-script.sh)}"
`

// localstackFaultReason is the same for every fault, because the reason is
// a property of the tool and not of the verb: LocalStack has no fault
// injection in the edition this was verified against.
const localstackFaultReason = "localstack emulates the AWS API and injects no faults (its Chaos API is a Pro feature, not verified here) — " +
	"inject this against the emulator's endpoint with tortureu emit pumba, netem or iptables"

// localstackNote explains why there is nothing to emit, distinguishing the
// three not-emitting cases the way protocol.go's noDepNote does: our input
// missing, the predicate verifiably false, and the predicate undetermined
// (R-COV-6 — an unchecked fact is never reported as an absence).
func localstackNote(sys *detect.System) (string, bool) {
	if sys == nil {
		return "# tortureu emit localstack: the system could not be detected, so whether this repo\n" +
			"# talks to AWS (dep:aws) is unknown; nothing to emit.\n", false
	}
	if _, ok := findDep(sys, "aws"); ok {
		return "", true
	}
	switch sys.Coverage.AWS {
	case detect.FactTrue:
		return "", true
	case detect.FactUnknown:
		return "# tortureu emit localstack: platform:aws is undetermined — the only manifest present is\n" +
			"# one detection does not parse (R-DET-14), so we could not check for an AWS SDK. That is\n" +
			"# not the same as there being none, so nothing to emit rather than a wrong answer.\n", false
	default:
		return "# tortureu emit localstack: no AWS SDK was found in any manifest and no localstack service\n" +
			"# exists in the compose file, so dep:aws does not hold; nothing to emit.\n", false
	}
}

// localstackServices returns the sorted, deduplicated LocalStack service
// names implied by detection's dependency list.
func localstackServices(sys *detect.System) []string {
	seen := map[string]bool{}
	var out []string
	for _, d := range sys.Deps {
		if svc, ok := localstackServiceTypes[d.Type]; ok && !seen[svc] {
			seen[svc] = true
			out = append(out, svc)
		}
	}
	sort.Strings(out)
	return out
}

// LocalStack generates the commands to run (or address) an AWS emulator for
// the detected AWS-using system (registry.yaml: when: dep:aws), and reports
// every fault as untranslated (R-CLI-8) because it translates none.
func LocalStack(cfg *config.Config, sys *detect.System) (string, error) {
	if note, ok := localstackNote(sys); !ok {
		return note, nil
	}

	var b strings.Builder
	b.WriteString(localstackHeader)

	b.WriteString("\n# ---- fault coverage ------------------------------------------------\n")
	for _, f := range cfg.Faults {
		b.WriteString(atComment(f))
		b.WriteString(skipComment("localstack", f, localstackFaultReason))
	}
	if len(cfg.Faults) == 0 {
		b.WriteString("# torture.yaml declares no faults: block.\n")
	}

	services := localstackServices(sys)
	endpoint := "http://localhost:" + localstackPort

	b.WriteString("\n# ---- the emulator --------------------------------------------------\n")
	if dep, ok := findDep(sys, "aws"); ok {
		host, port := hostPort(dep.Address)
		if port == "" {
			port = localstackPort
		}
		fmt.Fprintf(&b, "# Detection already found a LocalStack service in %s: %q at %s.\n", cfg.Target.Compose, dep.Name, dep.Address)
		b.WriteString("# Starting a second one would give you two emulators and one set of\n")
		b.WriteString("# endpoint variables, so this script only checks the existing one.\n")
		fmt.Fprintf(&b, "docker run --rm --network container:%s curlimages/curl -fs http://127.0.0.1:%s/_localstack/health\n", dep.Name, port)
		endpoint = fmt.Sprintf("http://%s:%s", host, port)
	} else {
		if len(services) > 0 {
			fmt.Fprintf(&b, "# SERVICES is exactly what detection found this repo's clients use: %s.\n", strings.Join(services, ", "))
			fmt.Fprintf(&b, "docker run -d --name tortureu-localstack -p %s:%s \\\n", localstackPort, localstackPort)
			fmt.Fprintf(&b, "  -e SERVICES=%s -e AWS_DEFAULT_REGION=\"$AWS_REGION\" %s\n", strings.Join(services, ","), localstackImage)
		} else {
			b.WriteString("# No AWS service client (s3/sqs/dynamodb per R-DET-9) was detected, only an\n")
			b.WriteString("# AWS SDK, so SERVICES is left unset rather than guessed: the community image\n")
			b.WriteString("# then enables its default set. Narrow it with -e SERVICES=... yourself.\n")
			fmt.Fprintf(&b, "docker run -d --name tortureu-localstack -p %s:%s \\\n", localstackPort, localstackPort)
			fmt.Fprintf(&b, "  -e AWS_DEFAULT_REGION=\"$AWS_REGION\" %s\n", localstackImage)
		}
		fmt.Fprintf(&b, "until curl -fs %s/_localstack/health >/dev/null 2>&1; do sleep 2; done\n", endpoint)
		b.WriteString("# Tear down: docker rm -f tortureu-localstack\n")
	}

	b.WriteString("\n# Point the system under test at the emulator, e.g. in\n")
	fmt.Fprintf(&b, "# %s's environment for %q:\n", cfg.Target.Compose, cfg.Target.Service)
	fmt.Fprintf(&b, "#   AWS_ENDPOINT_URL: %s\n", endpoint)
	b.WriteString("#   AWS_ACCESS_KEY_ID: test          # LocalStack ignores credentials (verified)\n")
	b.WriteString("#   AWS_SECRET_ACCESS_KEY: test\n")
	b.WriteString("#   AWS_DEFAULT_REGION: <your AWS_REGION>\n")
	b.WriteString("# An SDK older than the AWS_ENDPOINT_URL convention needs a per-client\n")
	b.WriteString("# endpoint override instead; that is your SDK's call, not something\n")
	b.WriteString("# torture.yaml knows about.\n")
	return b.String(), nil
}

func init() {
	Register("hoverfly", func(cfg *config.Config, _ *detect.System) (string, error) { return Hoverfly(cfg) }, false)
	// localstack is gated on dep:aws, which only detection can answer, and
	// its SERVICES list is derived from detected clients — it must refuse
	// rather than guess when detection is absent.
	Register("localstack", LocalStack, true)
}
