package emit

import (
	"fmt"
	"strings"

	"github.com/jdb316/tortureu/internal/config"
	"github.com/jdb316/tortureu/internal/fault"
)

// netemHeader documents the one limitation that matters most: plain `tc
// netem` has no destination filter of its own (that needs a classful
// qdisc plus a u32/fw-mark filter, which this emit does not attempt to
// generate because we cannot vouch for a filter setup we haven't run
// against a real container). Every command below therefore impairs the
// WHOLE interface of the container it targets, not just traffic to one
// dependency. pumba's --target flag (see `tortureu emit pumba`) can scope
// to a destination; this cannot.
const netemHeader = `#!/usr/bin/env bash
# Generated by tortureu emit netem. Requires: docker, and iproute2 (tc)
# installed inside the target container, plus NET_ADMIN on it
# (docker run --cap-add=NET_ADMIN, or the equivalent compose entry).
#
# LIMITATION: raw tc netem has no per-destination filter. Each command
# below impairs the ENTIRE network interface of the named container, not
# just traffic to the fault's declared target. If you need to scope the
# effect to one destination, use "tortureu emit pumba" instead (pumba's
# --target flag does this for you).
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml). Run each block
# yourself when the fault's "at:" phase begins.
`

// Netem translates latency and bandwidth faults into tc qdisc netem
// commands (R-CLI-8 proposed). Every other verb is reported with a
// skipComment naming why, never silently dropped.
func Netem(cfg *config.Config) (string, error) {
	var b strings.Builder
	b.WriteString(netemHeader)
	found := false
	for _, f := range cfg.Faults {
		act, err := fault.Translate(f)
		if err != nil {
			return "", fmt.Errorf("emit netem: %w", err)
		}
		reason, translatable := netemReason(act)
		if !translatable {
			b.WriteString("\n" + atComment(f))
			b.WriteString(skipComment("netem", f, reason))
			continue
		}
		found = true
		container, _ := resolveContainer(cfg, f.Target)
		b.WriteString("\n" + atComment(f))
		b.WriteString(netemCommand(container, f, act.Toxic))
	}
	if !found {
		b.WriteString("\n# no latency or bandwidth faults found in torture.yaml's faults: block.\n")
	}
	return b.String(), nil
}

// netemReason reports whether act is one netem translates (latency,
// bandwidth) and, if not, why not — for skipComment.
func netemReason(act fault.Action) (reason string, ok bool) {
	switch {
	case act.Kind == fault.KindPassed:
		return fmt.Sprintf("owned by %s, not a network-interface fault", act.Owner), false
	case act.Kind == fault.KindDocker:
		return "a container-level fault (signal/stress), not a network-interface fault; see \"tortureu emit pumba\"", false
	case act.Kind == fault.KindToxic && act.Toxic.Disable:
		return "connection-refused semantics; tc netem cannot express this, see \"tortureu emit iptables\"", false
	case act.Kind == fault.KindToxic && (act.Toxic.Type == "latency" || act.Toxic.Type == "bandwidth"):
		return "", true
	case act.Kind == fault.KindToxic:
		return fmt.Sprintf("tc netem has no verified equivalent of Toxiproxy's %q toxic", act.Toxic.Type), false
	default:
		return "unrecognized action", false
	}
}

// netemCommand renders the add/sleep/del block for one latency or
// bandwidth fault against container.
func netemCommand(container string, f config.Fault, t *fault.Toxic) string {
	var b strings.Builder
	switch t.Type {
	case "latency":
		ms := t.Attributes["latency"]
		fmt.Fprintf(&b, "docker exec %s tc qdisc add dev eth0 root netem delay %dms", container, ms)
		if jitter, ok := t.Attributes["jitter"]; ok {
			fmt.Fprintf(&b, " %dms", jitter)
		}
		b.WriteString("\n")
	case "bandwidth":
		kbps := t.Attributes["rate"].(int)
		kbit := kbps * 8
		fmt.Fprintf(&b, "docker exec %s tc qdisc add dev eth0 root netem rate %dkbit\n", container, kbit)
	}
	if f.For != "" {
		fmt.Fprintf(&b, "sleep %s && docker exec %s tc qdisc del dev eth0 root\n", f.For, container)
	} else {
		fmt.Fprintf(&b, "# no for: duration given; remove manually: docker exec %s tc qdisc del dev eth0 root\n", container)
	}
	return b.String()
}
