// Chaos Mesh translation (R-CLI-8 proposed): the Kubernetes upgrade path.
// RESEARCH.md calls this the clean upgrade path — "same scenario, different
// executor" — because torture.yaml's faults: block already states the
// intent (what fails, when, for how long); this file only changes which
// runtime carries it out.
//
// Scope, honestly stated: torture.yaml has no concept of a pod, a
// namespace, or a label. To select the right workload, this emit assumes
// the common docker-compose -> Kubernetes convention of an "app: <service
// name>" label (as kompose and most hand-written manifests use) in the
// "default" namespace. That assumption is stated in the emitted header, not
// buried — anyone whose manifests use a different label MUST edit
// spec.selector before applying.
//
// Verification: no Chaos Mesh installation, cluster, or kubectl binary was
// available in this environment (checked once at implementation time; see
// the git history for this file). Held to the same line the emit package's
// first implementer drew for pumba (no binary -> unverified, said so): every
// document this file emits is checked by this package's own tests, which
// parse the emitted YAML back and assert the required CRD fields
// (apiVersion, kind, metadata.name, spec.selector, spec.mode, and
// spec.action where the CRD has one) are present, per Chaos Mesh's
// published CRD reference (https://chaos-mesh.org/docs/next/basic-features/
// and https://github.com/chaos-mesh/chaos-mesh/tree/master/api/v1alpha1).
// That is a structural check, not proof the cluster accepts it — the
// emitted header says exactly that, and TestChaosMesh_HeaderDisclosesNoLiveClusterValidation
// pins it so this claim cannot silently rot into an unearned one.
//
// Verb coverage: latency, bandwidth, and down (network target) map onto
// NetworkChaos's delay/bandwidth/partition actions; kill maps onto
// PodChaos's pod-kill; cpu maps onto StressChaos's cpu stressor. Every other
// verb (graceful, pause, mem, io, fd, cpu_limit, mem_limit, and anything a
// different layer owns) is reported skipped with the specific reason no
// Chaos Mesh action was found to vouch for — see chaosMeshDoc below. In
// particular: PodChaos has no confirmed action that reproduces SIGTERM
// (graceful) or SIGSTOP (pause) semantics distinctly from pod-kill's
// SIGKILL, and StressChaos's memory/io stressors want a byte-size string
// this fault's "80%"-shaped values don't carry — guessing either would be
// exactly the silent-narrowing R-CLI-8 forbids.
package emit

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/jdb316/tortureu/internal/config"
	"github.com/jdb316/tortureu/internal/fault"
	"gopkg.in/yaml.v3"
)

const chaosMeshHeader = `# Generated by tortureu emit chaosmesh. Requires: a Chaos Mesh
# installation (https://chaos-mesh.org) in the target cluster, providing the
# NetworkChaos, PodChaos and StressChaos CRDs (chaos-mesh.org/v1alpha1).
#
# ASSUMPTIONS this emit makes, since torture.yaml has no Kubernetes concept
# of pods, namespaces, or labels:
#   - every fault target is selected via spec.selector.labelSelectors:
#     {app: <name>} in the "default" namespace — the common docker-compose
#     -> Kubernetes convention (e.g. kompose's generated label, generalized
#     to "app"). Edit metadata.namespace / spec.selector below to match your
#     actual manifests if they label workloads differently.
#   - a fault targeting an external host (egress class mock/real/block, or
#     an unclassified target) is scoped via NetworkChaos's externalTargets +
#     direction fields rather than a pod selector, since no in-cluster pod
#     represents it. externalTargets requires Chaos Mesh's chaosd/tproxy-
#     backed partition support (v2.1+); older installs may reject it.
#   - a fault with no "for:" duration produces a CRD with no spec.duration,
#     which Chaos Mesh runs until it is deleted (kubectl delete -f ...),
#     not until torture.yaml's run ends — there is no k6 clock in a cluster
#     for it to end with (R-EXE-8 applies to every tool in this package).
#
# NOT VALIDATED against a live cluster or kubectl: no Chaos Mesh install and
# no kubectl were available in this environment. Each document below was
# structurally checked — this package's own tests parse every emitted
# document back and assert apiVersion/kind/metadata.name/spec.selector/
# spec.mode (and spec.action, where the CRD has one) are present, per Chaos
# Mesh's published CRD reference — but never applied to or accepted by a
# real cluster. Run "kubectl apply --dry-run=server -f -" against your own
# cluster before relying on this in a real run.
#
# at:/for:'s "at:" is NOT scheduled by this emit — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml). Apply each document
# yourself when the fault's "at:" phase begins.
`

// chaosMeshNamePattern strips everything outside a Kubernetes object name's
// legal alphabet (lowercase alphanumeric and '-') so a fault name like
// "pg_slow" becomes the valid "pg-slow" rather than a name the API server
// rejects.
var chaosMeshNamePattern = regexp.MustCompile(`[^a-z0-9-]+`)

func chaosMeshName(raw string) string {
	s := chaosMeshNamePattern.ReplaceAllString(strings.ToLower(raw), "-")
	s = strings.Trim(s, "-")
	if s == "" {
		s = "fault"
	}
	return s
}

// --- Chaos Mesh CRD shapes (chaos-mesh.org/v1alpha1) -----------------------
//
// Modeled as Go structs and rendered with yaml.Marshal rather than
// string-templated like this package's other emitters, specifically so the
// "parse what you emit" verification standard has something meaningful to
// parse: hand-templated YAML can look right and still be indentation-broken
// in a case the author didn't hand-check, where a struct marshal cannot be.

type cmMeta struct {
	Name      string `yaml:"name"`
	Namespace string `yaml:"namespace"`
}

type cmSelector struct {
	LabelSelectors map[string]string `yaml:"labelSelectors"`
}

type cmDelay struct {
	Latency string `yaml:"latency"`
	Jitter  string `yaml:"jitter,omitempty"`
}

type cmBandwidthSpec struct {
	Rate   string `yaml:"rate"`
	Limit  uint32 `yaml:"limit"`
	Buffer uint32 `yaml:"buffer"`
}

type cmNetworkChaosSpec struct {
	Action          string           `yaml:"action"`
	Mode            string           `yaml:"mode"`
	Selector        cmSelector       `yaml:"selector"`
	Direction       string           `yaml:"direction,omitempty"`
	ExternalTargets []string         `yaml:"externalTargets,omitempty"`
	Delay           *cmDelay         `yaml:"delay,omitempty"`
	Bandwidth       *cmBandwidthSpec `yaml:"bandwidth,omitempty"`
	Duration        string           `yaml:"duration,omitempty"`
}

type cmNetworkChaos struct {
	APIVersion string             `yaml:"apiVersion"`
	Kind       string             `yaml:"kind"`
	Metadata   cmMeta             `yaml:"metadata"`
	Spec       cmNetworkChaosSpec `yaml:"spec"`
}

type cmPodChaosSpec struct {
	Action      string     `yaml:"action"`
	Mode        string     `yaml:"mode"`
	Selector    cmSelector `yaml:"selector"`
	GracePeriod int64      `yaml:"gracePeriod"`
}

type cmPodChaos struct {
	APIVersion string         `yaml:"apiVersion"`
	Kind       string         `yaml:"kind"`
	Metadata   cmMeta         `yaml:"metadata"`
	Spec       cmPodChaosSpec `yaml:"spec"`
}

type cmCPUStressor struct {
	Workers int `yaml:"workers"`
	Load    int `yaml:"load"`
}

type cmStressors struct {
	CPU *cmCPUStressor `yaml:"cpu,omitempty"`
}

type cmStressChaosSpec struct {
	Mode      string      `yaml:"mode"`
	Selector  cmSelector  `yaml:"selector"`
	Stressors cmStressors `yaml:"stressors"`
	Duration  string      `yaml:"duration,omitempty"`
}

type cmStressChaos struct {
	APIVersion string            `yaml:"apiVersion"`
	Kind       string            `yaml:"kind"`
	Metadata   cmMeta            `yaml:"metadata"`
	Spec       cmStressChaosSpec `yaml:"spec"`
}

// ChaosMesh translates torture.yaml's faults: block into Chaos Mesh CRDs
// (R-CLI-8 proposed) — same scenario, different executor. It reuses
// internal/fault.Translate for fault semantics (never re-derives them) and
// reports, per fault, any verb it does not translate rather than dropping
// it (see chaosMeshDoc).
func ChaosMesh(cfg *config.Config) (string, error) {
	var b strings.Builder
	b.WriteString(chaosMeshHeader)
	found := false
	for _, f := range cfg.Faults {
		act, err := fault.Translate(f)
		if err != nil {
			return "", fmt.Errorf("emit chaosmesh: %w", err)
		}
		doc, reason, ok, err := chaosMeshDoc(cfg, f, act)
		if err != nil {
			return "", fmt.Errorf("emit chaosmesh: fault %q: %w", f.Name, err)
		}
		if !ok {
			b.WriteString("\n" + atComment(f))
			b.WriteString(skipComment("chaosmesh", f, reason))
			continue
		}
		found = true
		b.WriteString("\n---\n" + atComment(f))
		b.WriteString(doc)
	}
	if !found {
		b.WriteString("\n# no fault in torture.yaml's faults: block was translatable by chaosmesh emit.\n")
	}
	return b.String(), nil
}

// chaosMeshDoc renders one fault's Chaos Mesh CRD, or reports why it can't.
// err is only non-nil on a yaml.Marshal failure, which none of the static
// struct shapes above should ever produce — surfaced anyway rather than
// ignored, per this project's own no-silent-failure standard.
func chaosMeshDoc(cfg *config.Config, f config.Fault, act fault.Action) (doc, reason string, ok bool, err error) {
	switch {
	case act.Kind == fault.KindPassed:
		return "", fmt.Sprintf("owned by %s, not a network or container fault this translator covers", act.Owner), false, nil

	case act.Kind == fault.KindToxic && act.Toxic.Disable:
		doc, err = chaosMeshPartition(cfg, f)
		return doc, "", err == nil, err

	case act.Kind == fault.KindToxic && act.Toxic.Type == "latency":
		doc, err = chaosMeshDelay(cfg, f, act.Toxic)
		return doc, "", err == nil, err

	case act.Kind == fault.KindToxic && act.Toxic.Type == "bandwidth":
		doc, err = chaosMeshBandwidth(cfg, f, act.Toxic)
		return doc, "", err == nil, err

	case act.Kind == fault.KindToxic:
		return "", fmt.Sprintf("no verified Chaos Mesh translation of Toxiproxy's %q toxic", act.Toxic.Type), false, nil

	case act.Kind == fault.KindDocker && act.Docker.Kind == "kill":
		doc, err = chaosMeshPodKill(f, act.Docker)
		return doc, "", err == nil, err

	case act.Kind == fault.KindDocker && act.Docker.Kind == "stress" && act.Docker.Args["resource"] == "cpu":
		doc, err = chaosMeshStressCPU(f, act.Docker)
		return doc, "", err == nil, err

	case act.Kind == fault.KindDocker && (act.Docker.Kind == "graceful" || act.Docker.Kind == "pause"):
		return "", fmt.Sprintf("no verified Chaos Mesh action reproduces %q's signal semantics distinctly from pod-kill's SIGKILL — see this file's header", act.Docker.Kind), false, nil

	case act.Kind == fault.KindDocker && act.Docker.Kind == "stress":
		return "", fmt.Sprintf("StressChaos's %q stressor wants a byte-size/count shape this fault's value doesn't carry closely enough to vouch for", act.Docker.Args["resource"]), false, nil

	case act.Kind == fault.KindDocker:
		return "", fmt.Sprintf("no verified Chaos Mesh translation of docker action %q", act.Docker.Kind), false, nil

	default:
		return "", "unrecognized action", false, nil
	}
}

// chaosMeshNoDurationNote documents why a document has no spec.duration.
func chaosMeshNoDurationNote(f config.Fault) string {
	if f.For != "" {
		return ""
	}
	return "# no for: duration given; this experiment has no spec.duration and Chaos Mesh\n" +
		"# runs it until you delete it: kubectl delete -f - (or by name).\n"
}

func chaosMeshDelay(cfg *config.Config, f config.Fault, t *fault.Toxic) (string, error) {
	app, external := resolveContainer(cfg, f.Target)
	delay := &cmDelay{Latency: fmt.Sprintf("%vms", t.Attributes["latency"])}
	if jitter, has := t.Attributes["jitter"]; has {
		delay.Jitter = fmt.Sprintf("%vms", jitter)
	}
	spec := cmNetworkChaosSpec{
		Action:   "delay",
		Mode:     "all",
		Selector: cmSelector{LabelSelectors: map[string]string{"app": app}},
		Delay:    delay,
		Duration: f.For,
	}
	if external != "" {
		spec.Direction = "to"
		spec.ExternalTargets = []string{external}
	}
	return marshalNetworkChaos(f, spec)
}

func chaosMeshBandwidth(cfg *config.Config, f config.Fault, t *fault.Toxic) (string, error) {
	app, external := resolveContainer(cfg, f.Target)
	kbps, _ := t.Attributes["rate"].(int)
	spec := cmNetworkChaosSpec{
		Action:   "bandwidth",
		Mode:     "all",
		Selector: cmSelector{LabelSelectors: map[string]string{"app": app}},
		Bandwidth: &cmBandwidthSpec{
			// Chaos Mesh's rate string follows tc's own convention: a
			// number plus a bits-per-second suffix. Toxiproxy's rate
			// (Attributes["rate"]) is KB/s (Toxiproxy's own unit, see
			// internal/fault); *8 converts bytes/s -> bits/s, matching
			// netem.go's and pumba.go's identical conversion for the same
			// underlying value, so all three tools agree with each other.
			// Not run against a live Chaos Mesh install — verify the
			// resulting throughput once applied.
			Rate:   fmt.Sprintf("%dkbps", kbps*8),
			Limit:  20971520,
			Buffer: 10000,
		},
		Duration: f.For,
	}
	if external != "" {
		spec.Direction = "to"
		spec.ExternalTargets = []string{external}
	}
	return marshalNetworkChaos(f, spec)
}

func chaosMeshPartition(cfg *config.Config, f config.Fault) (string, error) {
	app, external := resolveContainer(cfg, f.Target)
	spec := cmNetworkChaosSpec{
		Action:    "partition",
		Mode:      "all",
		Selector:  cmSelector{LabelSelectors: map[string]string{"app": app}},
		Direction: "both",
		Duration:  f.For,
	}
	if external != "" {
		// A partition against an external host cannot also carry a pod
		// selector for that host (there isn't one) — direction stays
		// "both" (cut the SUT off from it entirely, matching Toxiproxy's
		// "down" semantics of a fully disabled proxy) and externalTargets
		// names it instead.
		spec.ExternalTargets = []string{external}
	}
	return marshalNetworkChaos(f, spec)
}

func marshalNetworkChaos(f config.Fault, spec cmNetworkChaosSpec) (string, error) {
	obj := cmNetworkChaos{
		APIVersion: "chaos-mesh.org/v1alpha1",
		Kind:       "NetworkChaos",
		Metadata:   cmMeta{Name: chaosMeshName(f.Name), Namespace: "default"},
		Spec:       spec,
	}
	out, err := yaml.Marshal(obj)
	if err != nil {
		return "", err
	}
	return chaosMeshNoDurationNote(f) + string(out), nil
}

func chaosMeshPodKill(f config.Fault, d *fault.DockerAction) (string, error) {
	obj := cmPodChaos{
		APIVersion: "chaos-mesh.org/v1alpha1",
		Kind:       "PodChaos",
		Metadata:   cmMeta{Name: chaosMeshName(f.Name), Namespace: "default"},
		Spec: cmPodChaosSpec{
			Action:      "pod-kill",
			Mode:        "all",
			Selector:    cmSelector{LabelSelectors: map[string]string{"app": d.Container}},
			GracePeriod: 0,
		},
	}
	out, err := yaml.Marshal(obj)
	if err != nil {
		return "", err
	}
	return string(out), nil
}

func chaosMeshStressCPU(f config.Fault, d *fault.DockerAction) (string, error) {
	workers, ok := d.Args["workers"].(int)
	if !ok || workers < 1 {
		workers = 1
	}
	load, _ := d.Args["cpu_percent"].(int)
	obj := cmStressChaos{
		APIVersion: "chaos-mesh.org/v1alpha1",
		Kind:       "StressChaos",
		Metadata:   cmMeta{Name: chaosMeshName(f.Name), Namespace: "default"},
		Spec: cmStressChaosSpec{
			Mode:      "all",
			Selector:  cmSelector{LabelSelectors: map[string]string{"app": d.Container}},
			Stressors: cmStressors{CPU: &cmCPUStressor{Workers: workers, Load: load}},
			Duration:  f.For,
		},
	}
	out, err := yaml.Marshal(obj)
	if err != nil {
		return "", err
	}
	return chaosMeshNoDurationNote(f) + string(out), nil
}
