// porcupine — linearizability checking over a request history (R-CLI-8
// proposed; registry.yaml: tier delegate, when: dep:etcd|dep:consul|
// dep:zookeeper, how: "tortureu emit porcupine", note: "linearizability
// check over our own request history").
//
// porcupine is a Go LIBRARY (github.com/anishathalye/porcupine, MIT), not
// a CLI: there is no command to emit. So what `tortureu emit porcupine`
// produces is a complete, compilable Go program — a checker with the
// key/value model, the history reader, and the exit-code contract already
// written — which the operator builds and runs over a history file.
//
// VERIFICATION STATUS (what was actually run, and what was not):
//
//   - VERIFIED for real, on this machine: the emitted program was written
//     to a temp module, "go mod init" + "go get
//     github.com/anishathalye/porcupine" (v1.3.0, the real library) + "go
//     build" all succeeded, and the resulting binary was run over three
//     histories: a linearizable one (exit 0), a history whose read no
//     linearization can explain (exit 1), and an empty file (exit 2).
//     TestPorcupine_EmittedProgramCompilesAndChecksRealHistories re-runs
//     exactly that under TORTUREU_NET_TESTS=1.
//
//   - NOT VERIFIED: no history from a real etcd/consul/zookeeper cluster
//     under fault was checked — this environment had no such cluster and
//     nothing in TortureU produces such a history yet (see the next
//     paragraph, which is the honest reason). The visualization output
//     (porcupine.VisualizePath) was not opened in a browser.
//
// WHAT A CASSETTE CAN AND CANNOT SUPPLY, stated rather than papered over.
// registry.yaml's note says "linearizability check over our own request
// history", and TortureU does hold a request history: the `capture`
// cassette (R-CLI-9). This emit originally documented that cassettes were
// unusable because an Entry carried only "seq" and "duration_ms" — no
// absolute call or return time — and a linearizability check is entirely
// about CONCURRENCY, i.e. which operations overlapped. R-CLI-13 closed
// that: an Entry now carries "call_ns"/"return_ns" on a per-cassette
// monotonic timeline, which is exactly the schema below.
//
// The surviving limit is a different one, and it is not about time. A
// cassette records HTTP exchanges; porcupine checks a register model, so
// something must decide which exchange is a get and which is a put, and on
// which key. That mapping is the application's own semantics — URL shape,
// method, and body meaning differ per service — and inferring it would
// fabricate the operations the checker reasons over, precisely as
// inventing timestamps once would have. So the emitted program reads a
// history whose schema it documents, and a cassette becomes usable once
// the caller supplies that op/key mapping.
//
// What it does NOT translate: every fault. porcupine consumes a history;
// it injects nothing. Each fault is reported, never dropped (R-CLI-8).
package emit

import (
	"fmt"
	"strings"

	"github.com/jd316/tortureu/internal/config"
	"github.com/jd316/tortureu/internal/detect"
	"github.com/jd316/tortureu/internal/fault"
)

// porcupineDepTypes are registry.yaml's gate for this tool
// (dep:etcd|dep:consul|dep:zookeeper): the linearizable stores whose
// consistency claim is worth checking. A system with none of them has
// nothing here to check.
var porcupineDepTypes = []string{"etcd", "consul", "zookeeper"}

const porcupineHeader = `// Generated by tortureu emit porcupine. This is a complete Go program:
//
//   mkdir torture-lin && cd torture-lin && go mod init torture-lin
//   go get github.com/anishathalye/porcupine
//   # save this output as main.go
//   go build -o check . && ./check history.jsonl
//
// porcupine (github.com/anishathalye/porcupine, MIT) is a library, not a
// CLI, which is why this emit produces a program rather than a command.
//
// VERIFICATION STATUS: this program was compiled against the real
// porcupine v1.3.0 and run over three histories — linearizable (exit 0),
// non-linearizable (exit 1), and empty (exit 2). NOT verified: any history
// from a real etcd/consul/zookeeper cluster under fault, and the HTML
// visualization output.
//
// HISTORY FORMAT — one JSON object per line:
//
//   {"client":0,"op":"put","key":"x","value":"1","call_ns":10,"return_ns":42}
//   {"client":1,"op":"get","key":"x","value":"1","call_ns":30,"return_ns":51}
//
//   client     the concurrent client/goroutine that issued it
//   op         "put" or "get"
//   key        the register being operated on (the history is partitioned
//              by key, so unrelated keys do not blow up the search)
//   value      the value written (put) or the value READ BACK (get)
//   call_ns    when the request was SENT   (any monotonic ns clock)
//   return_ns  when the response ARRIVED
//
// FEEDING THIS A TORTUREU CASSETTE. tortureu capture (R-CLI-9) writes
// call_ns/return_ns per exchange (R-CLI-13), so a cassette carries the real
// concurrency this check needs — that was once the blocker and is not any
// more. What a cassette does NOT carry is which exchange is a get or a put
// and on which key: that is your application's semantics, not something a
// generic HTTP recorder can know. Map your cassette's exchanges to
// kind/op/key/value yourself and keep call_ns/return_ns as recorded.
// Inventing that mapping would fabricate the operations the checker
// reasons about, turning an unverifiable run into a confident
// "linearizable". This emit refuses to do that.
//
// EXIT CODES: 0 = linearizable, 1 = NOT linearizable (a result about your
// system, not a tool failure), 2 = could not check (unreadable/empty
// history, or the search hit its time limit and returned Unknown). An
// undecided search is never reported as a pass.
//
// at:/for: are NOT scheduled by this program — it is a delegate-tier
// handoff (real output, separate timing, registry.yaml). It reads a
// history after the fact; it starts nothing.
`

// porcupineProgram is the emitted checker. It is a Go raw string literal,
// so it deliberately contains no backticks.
const porcupineProgram = `
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"time"

	"github.com/anishathalye/porcupine"
)

// entry is one line of the history file (see the header for the schema).
type entry struct {
	Client   int    "json:\"client\""
	Op       string "json:\"op\""
	Key      string "json:\"key\""
	Value    string "json:\"value\""
	CallNS   int64  "json:\"call_ns\""
	ReturnNS int64  "json:\"return_ns\""
}

type kvInput struct {
	Op    string
	Key   string
	Value string
}

type kvOutput struct {
	Value string
}

// kvModel is the classic single-register-per-key model: a put sets the
// register, a get must return whatever the register held at the point the
// linearization places it. Partitioning by key is what keeps the search
// tractable: operations on different keys cannot affect each other.
var kvModel = porcupine.Model{
	Partition: func(history []porcupine.Operation) [][]porcupine.Operation {
		byKey := map[string][]porcupine.Operation{}
		for _, op := range history {
			in := op.Input.(kvInput)
			byKey[in.Key] = append(byKey[in.Key], op)
		}
		keys := make([]string, 0, len(byKey))
		for k := range byKey {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		parts := make([][]porcupine.Operation, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, byKey[k])
		}
		return parts
	},
	Init: func() interface{} { return "" },
	Step: func(state, input, output interface{}) (bool, interface{}) {
		st := state.(string)
		in := input.(kvInput)
		out := output.(kvOutput)
		if in.Op == "put" {
			return true, in.Value
		}
		return out.Value == st, st
	},
	DescribeOperation: func(input, output interface{}) string {
		in := input.(kvInput)
		out := output.(kvOutput)
		if in.Op == "put" {
			return fmt.Sprintf("put(%s, %s)", in.Key, in.Value)
		}
		return fmt.Sprintf("get(%s) -> %s", in.Key, out.Value)
	},
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: check <history.jsonl> [visualization.html]")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not read the history: %v\n", err)
		os.Exit(2)
	}
	defer f.Close()

	var ops []porcupine.Operation
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1024*1024), 16*1024*1024)
	line := 0
	for sc.Scan() {
		line++
		text := sc.Text()
		if len(text) == 0 {
			continue
		}
		var e entry
		if err := json.Unmarshal([]byte(text), &e); err != nil {
			fmt.Fprintf(os.Stderr, "history line %d is not valid JSON: %v\n", line, err)
			os.Exit(2)
		}
		if e.Op != "put" && e.Op != "get" {
			fmt.Fprintf(os.Stderr, "history line %d: op %q is neither put nor get; this model knows no other operation\n", line, e.Op)
			os.Exit(2)
		}
		if e.ReturnNS < e.CallNS {
			fmt.Fprintf(os.Stderr, "history line %d: return_ns is before call_ns; the history is not usable\n", line)
			os.Exit(2)
		}
		ops = append(ops, porcupine.Operation{
			ClientId: e.Client,
			Input:    kvInput{Op: e.Op, Key: e.Key, Value: e.Value},
			Call:     e.CallNS,
			Output:   kvOutput{Value: e.Value},
			Return:   e.ReturnNS,
		})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "could not read the history: %v\n", err)
		os.Exit(2)
	}
	// An empty history is NOT a pass: there is nothing to check, and
	// reporting "linearizable" for it would be the silent-success failure
	// this project rejects everywhere.
	if len(ops) == 0 {
		fmt.Fprintln(os.Stderr, "empty history: nothing to check. This is not a pass — record operations with call_ns/return_ns first.")
		os.Exit(2)
	}

	result, info := porcupine.CheckOperationsVerbose(kvModel, ops, 60*time.Second)
	switch result {
	case porcupine.Ok:
		fmt.Printf("LINEARIZABLE: %d operations, no violation found\n", len(ops))
		os.Exit(0)
	case porcupine.Illegal:
		fmt.Printf("NOT LINEARIZABLE: %d operations; no total order explains this history\n", len(ops))
		if len(os.Args) > 2 {
			out, err := os.Create(os.Args[2])
			if err == nil {
				defer out.Close()
				if err := porcupine.Visualize(kvModel, info, out); err != nil {
					fmt.Fprintf(os.Stderr, "(could not write the visualization: %v)\n", err)
				} else {
					fmt.Printf("visualization written to %s\n", os.Args[2])
				}
			}
		}
		os.Exit(1)
	default:
		// porcupine.Unknown: the search hit its time limit. That is "we
		// could not check", never "it was fine" — a distinct exit code,
		// not a pass.
		fmt.Fprintf(os.Stderr, "UNDECIDED: the linearizability search timed out after 60s over %d operations. This is NOT a pass; shorten the history or raise the limit.\n", len(ops))
		os.Exit(2)
	}
}
`

// porcupineNoDepNote refuses when registry.yaml's gate is not met, and
// distinguishes "detection never ran" from "no such dependency" the way
// protocol.go's noDepNote does.
func porcupineNoDepNote(sys *detect.System) string {
	if sys == nil {
		return "// tortureu emit porcupine: the system could not be detected, so whether it runs\n" +
			"// a linearizable store (registry.yaml gates porcupine on dep:etcd|dep:consul|\n" +
			"// dep:zookeeper) is unknown; nothing to emit.\n"
	}
	return "// tortureu emit porcupine: no etcd, consul or zookeeper dependency was detected\n" +
		"// (dep:etcd|dep:consul|dep:zookeeper); there is no linearizable store here whose\n" +
		"// consistency claim this could check, so nothing to emit.\n"
}

// Porcupine emits a linearizability checker program for the detected
// etcd/consul/zookeeper dependency. It reports every fault as untranslated
// (a checker injects nothing) rather than dropping them (R-CLI-8).
func Porcupine(cfg *config.Config, sys *detect.System) (string, error) {
	var dep detect.Dep
	found := false
	for _, t := range porcupineDepTypes {
		if d, ok := findDep(sys, t); ok {
			dep, found = d, true
			break
		}
	}
	if !found {
		return porcupineNoDepNote(sys), nil
	}

	var b strings.Builder
	b.WriteString(porcupineHeader)
	fmt.Fprintf(&b, "//\n// Detected store: %s (%s) at %s — that is the system whose history this\n"+
		"// checker is meant to be pointed at. Nothing here connects to it: this program\n"+
		"// reads a history you recorded, it does not generate one.\n",
		dep.Name, dep.Type, porcupineAddress(dep))

	for _, f := range cfg.Faults {
		if _, err := fault.Translate(f); err != nil {
			return "", fmt.Errorf("emit porcupine: %w", err)
		}
		b.WriteString("//\n")
		b.WriteString(porcupineComment(atComment(f)))
		b.WriteString(porcupineComment(skipComment("porcupine", f, "a linearizability checker consumes a history; it injects nothing — "+
			"inject this with \"tortureu emit pumba\", \"netem\" or \"iptables\", then check the history it produced")))
	}

	b.WriteString(porcupineProgram)
	return b.String(), nil
}

// porcupineAddress reports the dependency's address, or says it is unknown
// rather than printing an empty string that reads like a real value.
func porcupineAddress(dep detect.Dep) string {
	if dep.Address == "" {
		return "an address detection could not derive (R-DET-4)"
	}
	return dep.Address
}

// porcupineComment converts one shared "# ..." comment line (common.go's
// atComment/skipComment, written for the bash emitters) into a Go comment.
func porcupineComment(line string) string {
	var out strings.Builder
	for _, l := range strings.Split(strings.TrimRight(line, "\n"), "\n") {
		out.WriteString("// " + strings.TrimPrefix(l, "# ") + "\n")
	}
	return out.String()
}

func init() {
	// needsSystem: the gate (dep:etcd|dep:consul|dep:zookeeper) is a
	// detection fact, not a torture.yaml one.
	Register("porcupine", Porcupine, true)
}
