// Protocol-load and host-fault emit targets (SPEC.md R-CLI-8 proposed),
// added alongside the pumba/netem/iptables group in emit.go/pumba.go/
// netem.go/iptables.go.
//
// # Why this file does not touch emit.go
//
// Three agents extended `emit` concurrently against the same package. To
// avoid stepping on the other two, this file was scoped to only
// protocol.go/protocol_test.go, registering itself via init() rather than
// editing emit.go's Tools slice or Emit's switch (a shared dispatch table
// another agent's own tools also need to land in).
//
// That constraint has a real consequence, stated here rather than hidden:
// emit.go's Emit(tool, cfg) takes only a *config.Config, but two of this
// file's tools (Sysbench, Memtier — "protocol load driven by the detected
// dependency") need internal/detect's *detect.System to find the
// dependency's real address (R-DET-4) rather than guessing a port. There is
// no registry hook in emit.go for a second file to plug an extra parameter
// into Emit's existing signature without editing it. So `tortureu emit
// sysbench` does NOT work yet: EmitProtocol below is a fully real,
// independently tested entry point, but cmd/tortureu/emit.go (which this
// task also forbade touching) still only calls emit.Emit. Wiring
// `tortureu emit <tool>` up to EmitProtocol is a small, mechanical
// follow-up for whoever integrates this file — not attempted here per the
// collision-avoidance instructions ("say so and stop rather than editing
// shared code").
package emit

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/jdb316/tortureu/internal/config"
	"github.com/jdb316/tortureu/internal/detect"
	"github.com/jdb316/tortureu/internal/fault"
)

// ProtocolTools is every tool name this file implements, kept separate
// from emit.go's Tools var per the package doc above.
var ProtocolTools = []string{"fio", "clockskew", "sysbench", "memtier"}

// protocolDispatch is populated by init() below — the "register via
// init()" this task asked for, scoped to this file's own map rather than
// emit.go's switch.
var protocolDispatch = map[string]func(*config.Config, *detect.System) (string, error){}

func init() {
	protocolDispatch["fio"] = Fio
	protocolDispatch["clockskew"] = func(cfg *config.Config, _ *detect.System) (string, error) { return ClockSkew(cfg) }
	protocolDispatch["sysbench"] = Sysbench
	protocolDispatch["memtier"] = Memtier
}

// EmitProtocol is this file's own entry point (see package doc: emit.go's
// Emit does not dispatch here yet). sys may be nil for tools that don't
// need detection (clockskew, fio's applicability check degrades to a
// generic directory guess without it).
func EmitProtocol(tool string, cfg *config.Config, sys *detect.System) (string, error) {
	fn, ok := protocolDispatch[tool]
	if !ok {
		names := make([]string, 0, len(protocolDispatch))
		for k := range protocolDispatch {
			names = append(names, k)
		}
		sort.Strings(names)
		return "", fmt.Errorf("tortureu emit: unknown tool %q; supported by the protocol/host-fault group: %s", tool, strings.Join(names, ", "))
	}
	return fn(cfg, sys)
}

// ---------------------------------------------------------------------
// fio — disk IO pressure (registry.yaml: dep:postgresql|dep:mysql|dep:mongodb)
// ---------------------------------------------------------------------

// dataDirByType is the well-known data directory each dependency type's
// official Docker image writes to. Used to point fio at the volume that
// actually matters ("fsync latency is where DBs die", registry.yaml)
// instead of an arbitrary path that might not even share the same
// filesystem/volume.
var dataDirByType = map[string]string{
	"postgresql": "/var/lib/postgresql/data",
	"mysql":      "/var/lib/mysql",
	"mongodb":    "/data/db",
}

const fioHeader = `#!/usr/bin/env bash
# Generated by tortureu emit fio. Requires: docker, and fio installed
# INSIDE the target container. Most official postgres/mysql/mongo images
# do NOT ship fio — you will need a custom image, or to install it at
# container start (e.g. an apt-get layer), before this docker exec works.
#
# VERIFICATION STATUS: the fio flags below (randrw, --bs, --size,
# --numjobs, --runtime/--time_based) were run for real on the host
# machine against a scratch directory and produced real IOPS/bandwidth
# numbers (67.5k IOPS, 264MiB/s on this machine). They were NOT run
# inside a live database container for this emit: copying a static fio
# binary into an unmodified mysql:8.0 container failed with a missing
# libnuma.so.1, and that is reported here rather than silently assumed
# away. Verify fio's own --help against whatever you bake into your
# image before relying on this in a real run.
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml). Run each block
# yourself when the fault's "at:" phase begins.
`

// Fio translates "io" resource-pressure faults (R-CFG-14) into fio
// commands run inside the fault's target container. sys, when non-nil, is
// used to point --directory at the dependency's real data directory
// (dataDirByType) rather than a generic path; without it (sys == nil, or
// the target isn't a detected dependency) the command falls back to /tmp
// and says so in a comment, per R-COV-6 (report undetermined, don't
// guess a data path that might not even be on the impaired volume).
//
// Every other fault verb is reported skipped via skipComment (R-CLI-8),
// mirroring netem.go/pumba.go's own pattern.
func Fio(cfg *config.Config, sys *detect.System) (string, error) {
	var b strings.Builder
	b.WriteString(fioHeader)
	found := false
	for _, f := range cfg.Faults {
		act, err := fault.Translate(f)
		if err != nil {
			return "", fmt.Errorf("emit fio: %w", err)
		}
		reason, ok := fioReason(act)
		b.WriteString("\n" + atComment(f))
		if !ok {
			b.WriteString(skipComment("fio", f, reason))
			continue
		}
		found = true
		container, _ := resolveContainer(cfg, f.Target)
		dir, guessed := fioDataDir(f.Target, sys)
		b.WriteString(fioCommand(container, f, act.Docker, dir, guessed))
	}
	if !found {
		b.WriteString("\n# no disk-io faults (inject: io) found in torture.yaml's faults: block.\n")
	}
	return b.String(), nil
}

// fioReason reports whether act is the one fio translates (an "io"
// resource-pressure Docker action) and, if not, why not.
func fioReason(act fault.Action) (reason string, ok bool) {
	switch {
	case act.Kind == fault.KindPassed:
		return fmt.Sprintf("owned by %s, not a service resource fault", act.Owner), false
	case act.Kind == fault.KindToxic:
		return "a network fault, not disk IO; see \"tortureu emit netem\" or \"tortureu emit pumba\"", false
	case act.Kind == fault.KindDocker && act.Docker.Kind == "stress" && act.Docker.Args["resource"] == "io":
		return "", true
	case act.Kind == fault.KindDocker:
		return fmt.Sprintf("a %q service fault (resource %v), not disk IO", act.Docker.Kind, act.Docker.Args["resource"]), false
	default:
		return "unrecognized action", false
	}
}

// fioDataDir picks the directory fio should target: the dependency's
// well-known data directory when sys identifies target's type, else /tmp
// with guessed=true so the caller can flag the fallback.
func fioDataDir(target string, sys *detect.System) (dir string, guessed bool) {
	host, _ := hostPort(target)
	if sys != nil {
		for _, d := range sys.Deps {
			if d.Name == host {
				if dataDir, ok := dataDirByType[d.Type]; ok {
					return dataDir, false
				}
			}
		}
	}
	return "/tmp", true
}

// fioCommand renders one "io" fault's docker exec fio invocation.
func fioCommand(container string, f config.Fault, d *fault.DockerAction, dir string, dirGuessed bool) string {
	size := fioSize(d.Args["amount"])
	numjobs := 1
	if w, ok := d.Args["workers"]; ok {
		if n, ok2 := asPositiveInt(w); ok2 {
			numjobs = n
		}
	}
	var b strings.Builder
	if dirGuessed {
		fmt.Fprintf(&b, "# no detected dependency data directory for target %q; defaulting --directory to /tmp (edit to the real data volume path)\n", f.Target)
	}
	runtimeFlag := ""
	if f.For != "" {
		if secs, ok := parseSeconds(f.For); ok {
			runtimeFlag = fmt.Sprintf(" --runtime=%ds --time_based", secs)
		}
	}
	fmt.Fprintf(&b, "docker exec %s fio --name=torture_io_%s --directory=%s --rw=randrw --bs=4k --size=%s --numjobs=%d --group_reporting%s\n",
		container, f.Name, dir, size, numjobs, runtimeFlag)
	if runtimeFlag == "" {
		b.WriteString("# no for: duration given; fio runs until --size is written instead of a fixed window — add for: to bound it\n")
	}
	return b.String()
}

// fioSizePattern accepts fio's own size suffix grammar (k/m/g, case
// insensitive) or a bare number of bytes.
var fioSizePattern = regexp.MustCompile(`(?i)^\d+[kmgt]?$`)

// fioSize converts the "io" verb's raw amount (config.Fault.Inject["io"],
// carried through as fault.DockerAction.Args["amount"]) to an fio --size
// value. torture.yaml's grammar (R-CFG-14) does not define what "io"'s
// value means beyond "resource pressure" — this emit interprets it as an
// fio size string (e.g. "500m", "1g") when it already looks like one, and
// falls back to a documented default otherwise, rather than guessing a
// number silently.
func fioSize(amount any) string {
	if s, ok := amount.(string); ok && fioSizePattern.MatchString(s) {
		return s
	}
	return "1g"
}

func asPositiveInt(v any) (int, bool) {
	switch n := v.(type) {
	case int:
		return n, n > 0
	case int64:
		return int(n), n > 0
	case float64:
		return int(n), n > 0
	default:
		return 0, false
	}
}

// secondsPattern accepts a bare integer number of seconds or a number
// with an "s"/"m"/"h" suffix, mirroring config.Fault.For's own grammar
// (R-CFG-11 uses the same duration shorthand for at:+<duration>).
var secondsPattern = regexp.MustCompile(`(?i)^(\d+)(s|m|h)?$`)

func parseSeconds(s string) (int, bool) {
	m := secondsPattern.FindStringSubmatch(strings.TrimSpace(s))
	if m == nil {
		return 0, false
	}
	n, err := strconv.Atoi(m[1])
	if err != nil {
		return 0, false
	}
	switch strings.ToLower(m[2]) {
	case "m":
		n *= 60
	case "h":
		n *= 3600
	}
	return n, true
}

// ---------------------------------------------------------------------
// clockskew — libfaketime (registry.yaml: always)
// ---------------------------------------------------------------------

// faketimeLibPath is where Debian/Ubuntu's libfaketime package installs
// the LD_PRELOAD shim — the distro this emit's own verification ran on.
// A different base image may install it elsewhere; the header says so.
const faketimeLibPath = "/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1"

const clockskewHeaderTemplate = `#!/usr/bin/env bash
# Generated by tortureu emit clockskew. Requires: docker, and libfaketime
# installed INSIDE the target container's image (Debian/Ubuntu:
# "apt-get install libfaketime"; the LD_PRELOAD path below assumes that
# package's layout at %s — check your image's own path if it differs).
#
# LIMITATION: libfaketime works via LD_PRELOAD, which only takes effect
# when a process execs. It CANNOT retroactively skew the clock of a
# service's own already-running PID 1. Step 1 below proves the mechanism
# on a freshly exec'd process (docker exec always execs a new one); step
# 2 is how you actually skew the SUT's real running server — force it to
# re-exec under the skew via a compose override.
#
# torture.yaml's faults: grammar (R-CFG-14) has no clockskew verb, so
# this command's offset is not read from a fault entry: edit FAKETIME
# below to the skew you want to test. Three real motivating cases named
# in registry.yaml: JWT exp ("+1h" forward), cache TTL ("+10m" forward),
# leader lease ("-30s" backward, a clock that runs behind).
#
# VERIFIED for real on this host: "faketime '+2 years' date -u" and the
# equivalent LD_PRELOAD/FAKETIME env-var form both skewed "date -u"'s
# output by exactly the requested offset. NOT verified inside a live
# docker container: copying the host's libfaketime.so.1 into a running
# mysql:8.0 container failed with a GLIBC version mismatch against that
# container's older glibc — a cross-image binary-copy problem, not a
# defect in the LD_PRELOAD/FAKETIME mechanism itself. Installing
# libfaketime from the target image's own package manager (as the header
# above recommends) avoids this; that path was not itself re-verified
# inside a container due to time, and is reported as such rather than
# implied to be.
`

// ClockSkew generates a libfaketime-based clock-skew command for the SUT
// service (registry.yaml: always — this tool has no fault-verb gate, so
// it does not iterate cfg.Faults the way Fio/Netem/Pumba/IPTables do).
func ClockSkew(cfg *config.Config) (string, error) {
	const offset = "+1h"
	container := cfg.Target.Service
	var b strings.Builder
	fmt.Fprintf(&b, clockskewHeaderTemplate, faketimeLibPath)
	fmt.Fprintf(&b, "\nFAKETIME=%q\n\n", offset)
	b.WriteString("# 1) verify the mechanism on a fresh process (does NOT affect the running server):\n")
	fmt.Fprintf(&b, "docker exec -e LD_PRELOAD=%s -e FAKETIME=\"$FAKETIME\" %s date -u\n\n", faketimeLibPath, container)
	fmt.Fprintf(&b, "# 2) apply it to the SUT itself: add to %s's service entry for %q in a compose\n", cfg.Target.Compose, container)
	fmt.Fprintf(&b, "#    override, then `docker compose -f %s up -d --force-recreate %s`:\n", cfg.Target.Compose, container)
	b.WriteString("#      environment:\n")
	fmt.Fprintf(&b, "#        LD_PRELOAD: %s\n", faketimeLibPath)
	fmt.Fprintf(&b, "#        FAKETIME: %q\n", offset)
	return b.String(), nil
}

// ---------------------------------------------------------------------
// sysbench / memtier — protocol load (registry.yaml: dep:mysql, dep:redis)
// ---------------------------------------------------------------------

// findDep returns the first detected dependency of the given
// registry.yaml type (R-DET-9 vocabulary), or ok=false when detection
// found none — the R-COV-6 "report undetermined" case, never a guessed
// address.
func findDep(sys *detect.System, depType string) (detect.Dep, bool) {
	if sys == nil {
		return detect.Dep{}, false
	}
	for _, d := range sys.Deps {
		if d.Type == depType {
			return d, true
		}
	}
	return detect.Dep{}, false
}

// noDepNote explains why a dependency-addressed emitter has nothing to
// emit. A nil sys means detection never ran or failed — reporting that as
// "no such dependency" would blame the user's compose file for our own
// missing input, so the two cases say different things.
func noDepNote(tool string, sys *detect.System, depType string) string {
	if sys == nil {
		return fmt.Sprintf("# tortureu emit %s: the system could not be detected, so the %s address is unknown; nothing to emit.\n", tool, depType)
	}
	return fmt.Sprintf("# tortureu emit %s: no %s dependency was detected (dep:%s); nothing to emit.\n", tool, depType, depType)
}

// peakRPS scans load.stages (R-CFG-6..8) for the highest to:/hold: rate
// (torture.yaml's "<n>rps" grammar, see torture.example.yaml), used as a
// concurrency proxy for the protocol-load tools below: neither sysbench
// nor memtier speaks arrival-rate natively, so this maps the SAME peak
// intensity the k6 profile is driving into their own thread/client counts
// rather than picking an arbitrary constant.
var rpsPattern = regexp.MustCompile(`(?i)^(\d+)rps$`)

func peakRPS(load config.Load) (int, bool) {
	best := 0
	found := false
	for _, s := range load.Stages {
		for _, v := range []string{s.To, s.Hold} {
			if m := rpsPattern.FindStringSubmatch(v); m != nil {
				n, err := strconv.Atoi(m[1])
				if err == nil && n > best {
					best = n
					found = true
				}
			}
		}
	}
	return best, found
}

// totalSeconds sums load.stages' over:/for: durations (R-CFG-8), used as
// the protocol-load tools' --time/--test-time window when the profile
// declares one.
func totalSeconds(load config.Load) (int, bool) {
	total := 0
	found := false
	for _, s := range load.Stages {
		for _, v := range []string{s.Over, s.For} {
			if v == "" {
				continue
			}
			if secs, ok := parseSeconds(v); ok {
				total += secs
				found = true
			}
		}
	}
	return total, found
}

// concurrencyFromRPS is the mapping peakRPS documents: one worker per 50
// req/s of peak load, floor 4 (below that, a single generator process can
// usually saturate a local dependency on its own) and ceiling 64 (both
// sysbench and memtier document diminishing returns, and thread-per-conn
// tools stop being a fair load generator well before real production
// concurrency anyway).
func concurrencyFromRPS(rps int) int {
	n := rps / 50
	if n < 4 {
		n = 4
	}
	if n > 64 {
		n = 64
	}
	return n
}

const sysbenchHeader = `#!/usr/bin/env bash
# Generated by tortureu emit sysbench. Requires: docker.
#
# Reaches the detected mysql dependency's own container network namespace
# via "--network container:<dep>" rather than guessing a docker-compose
# network name (none is recorded in torture.yaml) or requiring the port
# be published to the host. This borrows the dependency container's
# netns, so "127.0.0.1" below IS that dependency, and its compose-internal
# DNS still resolves for anything else you add.
#
# --mysql-user/--mysql-password/--mysql-db are placeholders: torture.yaml
# carries no database credentials (out of its schema), so these are not
# derived from anything — edit them before running.
#
# VERIFIED for real: this exact command shape (severalnines/sysbench,
# oltp_read_write, prepare/run/cleanup, --network container:<name>) was
# run against a live mysql:8.0 container on this host and produced real
# transactions (896 events, 178.5 tps, p95 31.9ms over a 5s run).
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml).
`

// Sysbench generates a sysbench oltp_read_write prepare/run/cleanup
// sequence against the detected mysql dependency (registry.yaml:
// when: dep:mysql), sized from load.stages' peak rate and total duration
// when torture.yaml declares a load: block.
func Sysbench(cfg *config.Config, sys *detect.System) (string, error) {
	dep, ok := findDep(sys, "mysql")
	if !ok {
		return noDepNote("sysbench", sys, "mysql"), nil
	}
	_, port := hostPort(dep.Address)
	if port == "" {
		port = "3306"
	}
	threads := 4
	if rps, ok := peakRPS(cfg.Load); ok {
		threads = concurrencyFromRPS(rps)
	}
	seconds := 60
	if total, ok := totalSeconds(cfg.Load); ok && total > 0 {
		seconds = total
	}

	var b strings.Builder
	b.WriteString(sysbenchHeader)
	fmt.Fprintf(&b, "\n# sized from torture.yaml's load: block: peak rate -> %d threads, total stage duration -> %ds\n", threads, seconds)
	base := fmt.Sprintf("docker run --rm --network container:%s severalnines/sysbench sysbench oltp_read_write "+
		"--db-driver=mysql --mysql-host=127.0.0.1 --mysql-port=%s "+
		"--mysql-user=CHANGE_ME --mysql-password=CHANGE_ME --mysql-db=CHANGE_ME "+
		"--tables=10 --table-size=100000 --threads=%d", dep.Name, port, threads)
	fmt.Fprintf(&b, "%s prepare\n", base)
	fmt.Fprintf(&b, "%s --time=%d run\n", base, seconds)
	fmt.Fprintf(&b, "%s cleanup\n", base)
	return b.String(), nil
}

const memtierHeader = `#!/usr/bin/env bash
# Generated by tortureu emit memtier. Requires: docker.
#
# Same "--network container:<dep>" reasoning as "tortureu emit sysbench"
# (see its header) — reaches the detected redis dependency without
# guessing a compose network name or requiring a published port.
#
# VERIFIED for real: this exact command shape (redislabs/memtier_benchmark,
# --network container:<name>) was run against a live redis:7-alpine
# container on this host and produced real throughput (60.7k ops/sec
# combined GET/SET over a short run).
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml).
`

// Memtier generates a memtier_benchmark invocation against the detected
// redis dependency (registry.yaml: when: dep:redis), sized the same way
// Sysbench is.
func Memtier(cfg *config.Config, sys *detect.System) (string, error) {
	dep, ok := findDep(sys, "redis")
	if !ok {
		return noDepNote("memtier", sys, "redis"), nil
	}
	_, port := hostPort(dep.Address)
	if port == "" {
		port = "6379"
	}
	clients := 4
	if rps, ok := peakRPS(cfg.Load); ok {
		clients = concurrencyFromRPS(rps)
	}
	seconds := 60
	if total, ok := totalSeconds(cfg.Load); ok && total > 0 {
		seconds = total
	}

	var b strings.Builder
	b.WriteString(memtierHeader)
	fmt.Fprintf(&b, "\n# sized from torture.yaml's load: block: peak rate -> %d clients, total stage duration -> %ds\n", clients, seconds)
	fmt.Fprintf(&b, "docker run --rm --network container:%s redislabs/memtier_benchmark "+
		"memtier_benchmark --server=127.0.0.1 --port=%s --clients=%d --threads=4 --test-time=%d --hide-histogram\n",
		dep.Name, port, clients, seconds)
	return b.String(), nil
}

func init() {
	// fio, sysbench and memtier need a real dependency address from
	// detection; they must refuse rather than guess a host or port.
	Register("fio", Fio, true)
	Register("sysbench", Sysbench, true)
	Register("memtier", Memtier, true)
	Register("clockskew", func(cfg *config.Config, _ *detect.System) (string, error) { return ClockSkew(cfg) }, false)
}
