package emit

import (
	"fmt"
	"strings"

	"github.com/jd316/TortureU/internal/config"
	"github.com/jd316/TortureU/internal/fault"
)

// pumbaHeader documents pumba's real advantage over raw tc/iptables: its
// --target flag scopes a netem effect to one destination without hand-
// rolled tc filters, and it wraps container signals/stress-ng itself, so
// one tool covers more of the fault-verb space credibly than the other
// two. It still does not cover everything: down (connection-refused
// semantics), mem/io/fd stress (pumba's own stress-ng flag for these does
// not map onto our workers/amount schema closely enough to vouch for), and
// anything owned by another layer (error_rate, poison_pill, duplicate) are
// all reported as skipped rather than guessed.
const pumbaHeader = `#!/usr/bin/env bash
# Generated by tortureu emit pumba. Requires: docker, and pumba on PATH
# (https://github.com/alexei-led/pumba) with access to the docker socket.
#
# --time/--jitter below are plain milliseconds per pumba's own netem delay
# flags; --rate is tc's own "<n>kbit" syntax. Verify against your installed
# pumba's --help before relying on this in a real run — this emit was not
# executed against a live pumba binary.
#
# at:/for: are NOT scheduled by this script — this is a delegate-tier
# handoff (real output, separate timing, registry.yaml). Run each block
# yourself when the fault's "at:" phase begins; pumba's own --duration
# handles the "for:" window natively, so no manual teardown is needed here
# (unlike netem/iptables emit).
`

// Pumba translates network faults (via pumba netem, scoped with --target)
// and container-level faults (kill, graceful, pause, cpu stress) into
// pumba commands (R-CLI-8 proposed). Everything else is reported skipped.
func Pumba(cfg *config.Config) (string, error) {
	var b strings.Builder
	b.WriteString(pumbaHeader)
	found := false
	for _, f := range cfg.Faults {
		act, err := fault.Translate(f)
		if err != nil {
			return "", fmt.Errorf("emit pumba: %w", err)
		}
		cmd, reason, ok := pumbaCommand(cfg, f, act)
		b.WriteString("\n" + atComment(f))
		if !ok {
			b.WriteString(skipComment("pumba", f, reason))
			continue
		}
		found = true
		b.WriteString(cmd)
	}
	if !found {
		b.WriteString("\n# no fault in torture.yaml's faults: block was translatable by pumba emit.\n")
	}
	return b.String(), nil
}

// pumbaCommand renders one fault's pumba command, or reports why it can't.
func pumbaCommand(cfg *config.Config, f config.Fault, act fault.Action) (cmd, reason string, ok bool) {
	switch {
	case act.Kind == fault.KindPassed:
		return "", fmt.Sprintf("owned by %s, not a network or container fault", act.Owner), false

	case act.Kind == fault.KindToxic && act.Toxic.Disable:
		return "", "connection-refused semantics; pumba's netem/kill/stop subcommands don't express this, see \"tortureu emit iptables\"", false

	case act.Kind == fault.KindToxic && act.Toxic.Type == "latency":
		container, scope := resolveContainer(cfg, f.Target)
		ms := act.Toxic.Attributes["latency"]
		var b strings.Builder
		duration := f.For
		if duration == "" {
			duration = "10s"
		}
		fmt.Fprintf(&b, "pumba netem --duration %s delay --time %v", duration, ms)
		if jitter, has := act.Toxic.Attributes["jitter"]; has {
			fmt.Fprintf(&b, " --jitter %v", jitter)
		}
		if scope != "" {
			fmt.Fprintf(&b, " --target %s", scope)
		}
		fmt.Fprintf(&b, " %s\n", container)
		if f.For == "" {
			b.WriteString("# no for: duration given; defaulted --duration to 10s above, edit as needed\n")
		}
		return b.String(), "", true

	case act.Kind == fault.KindToxic && act.Toxic.Type == "bandwidth":
		container, scope := resolveContainer(cfg, f.Target)
		kbps := act.Toxic.Attributes["rate"].(int)
		kbit := kbps * 8
		duration := f.For
		if duration == "" {
			duration = "10s"
		}
		var b strings.Builder
		fmt.Fprintf(&b, "pumba netem --duration %s rate --rate %dkbit", duration, kbit)
		if scope != "" {
			fmt.Fprintf(&b, " --target %s", scope)
		}
		fmt.Fprintf(&b, " %s\n", container)
		if f.For == "" {
			b.WriteString("# no for: duration given; defaulted --duration to 10s above, edit as needed\n")
		}
		return b.String(), "", true

	case act.Kind == fault.KindToxic:
		return "", fmt.Sprintf("pumba has no verified equivalent of Toxiproxy's %q toxic", act.Toxic.Type), false

	case act.Kind == fault.KindDocker && act.Docker.Kind == "kill":
		return fmt.Sprintf("pumba kill --signal %s %s\n", act.Docker.Args["signal"], act.Docker.Container), "", true

	case act.Kind == fault.KindDocker && act.Docker.Kind == "graceful":
		return fmt.Sprintf("pumba kill --signal %s %s\n", act.Docker.Args["signal"], act.Docker.Container), "", true

	case act.Kind == fault.KindDocker && act.Docker.Kind == "pause":
		duration := f.For
		if duration == "" {
			return "", "pumba pause requires a for: duration and this fault has none", false
		}
		return fmt.Sprintf("pumba pause --duration %s %s\n", duration, act.Docker.Container), "", true

	case act.Kind == fault.KindDocker && act.Docker.Kind == "stress" && act.Docker.Args["resource"] == "cpu":
		duration := f.For
		if duration == "" {
			duration = "10s"
		}
		workers := act.Docker.Args["workers"]
		if workers == nil {
			workers = 1
		}
		stressors := fmt.Sprintf("--cpu %v --cpu-load %v", workers, act.Docker.Args["cpu_percent"])
		return fmt.Sprintf("pumba stress --duration %s --stress-image alexeiled/stress-ng --stressors %q %s\n",
			duration, stressors, act.Docker.Container), "", true

	case act.Kind == fault.KindDocker && act.Docker.Kind == "stress":
		return "", fmt.Sprintf("pumba's stress-ng flags for %q don't map onto this fault's workers/amount schema closely enough to vouch for", act.Docker.Args["resource"]), false

	case act.Kind == fault.KindDocker:
		return "", fmt.Sprintf("no verified pumba translation for docker action %q", act.Docker.Kind), false

	default:
		return "", "unrecognized action", false
	}
}
