// Package k6 compiles the load block of a parsed torture.yaml into a k6
// script, and models k6's machine-readable output (SPEC.md §4.3, §5, §6).
//
// TortureU never imports k6 Go packages, links against k6, or builds an xk6
// extension into this binary (R-LIC-1): k6 is AGPL-3, and doing so would
// make this MIT project a derivative work. This package only ever produces
// text handed to a k6 process invoked separately, and parses text k6 itself
// wrote back out.
package k6

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/jdb316/tortureu/internal/config"
)

// PhaseMarkerPrefix tags a stage-transition marker line the generated script
// writes to stdout when a load phase begins (R-EXE-8). This is the "one
// clock" mechanism: the fault scheduler anchors `at: peak+30s` against this
// event, which is k6's own clock, not TortureU's wall clock.
const PhaseMarkerPrefix = "TORTUREU_PHASE_START"

// ParsePhaseMarker extracts the phase name from one line of k6 stdout, if
// that line is a stage-transition marker emitted by a script Compile
// produced (R-EXE-8). ok is false for any other line.
func ParsePhaseMarker(line string) (phase string, ok bool) {
	fields := strings.Fields(strings.TrimSpace(line))
	if len(fields) < 2 || fields[0] != PhaseMarkerPrefix {
		return "", false
	}
	return fields[1], true
}

// rpsPattern matches load.stages target values like "500rps" (R-CFG-8).
var rpsPattern = regexp.MustCompile(`^([0-9]+(?:\.[0-9]+)?)rps$`)

func parseRPS(s string) (float64, error) {
	m := rpsPattern.FindStringSubmatch(s)
	if m == nil {
		return 0, fmt.Errorf("k6: %q is not a valid rps value (want e.g. \"500rps\")", s)
	}
	return strconv.ParseFloat(m[1], 64)
}

// compiledStage is one load.stages entry resolved to the numbers the script
// template needs.
type compiledStage struct {
	Phase    string
	Target   float64
	Duration string
	StartAt  time.Duration
}

// Compile renders the load block of cfg into a k6 script.
//
//   - R-CFG-6: the only executor used is 'ramping-arrival-rate', k6's open
//     (arrival-rate) model. No VU-based closed-model executor is emitted.
//   - R-CFG-7/8: each load.stages entry becomes one arrival-rate stage, plus
//     its own 1-iteration marker scenario named after its (unique) phase.
//   - R-CFG-9: each scenario's flow steps become http.request calls keyed
//     on method and path.
//   - R-EXE-8: a marker scenario fires at each stage's start, logging a
//     PhaseMarkerPrefix line via k6's own execution clock.
//   - R-EXE-9: only built-in k6 modules ('k6/http', 'k6/execution') are
//     imported; nothing is fetched over the network at script load or run
//     time.
func Compile(cfg *config.Config) (string, error) {
	if cfg.Load.Model != "arrival_rate" {
		return "", fmt.Errorf("k6: load.model must be arrival_rate (open model), got %q", cfg.Load.Model)
	}
	if len(cfg.Load.Stages) == 0 {
		return "", fmt.Errorf("k6: load.stages must not be empty")
	}

	stages, maxTarget, err := resolveStages(cfg.Load.Stages)
	if err != nil {
		return "", err
	}

	scenarios, err := scenariosJSON(cfg.Load.Scenarios, cfg.Target.BaseURL)
	if err != nil {
		return "", err
	}

	maxVUs := int(maxTarget*5) + 10
	preAllocated := int(maxTarget) + 5

	var b strings.Builder
	b.WriteString("// Generated by tortureu. DO NOT EDIT.\n")
	b.WriteString("// R-LIC-1/R-LIC-2: this file is an input to k6, not a derivative work of it.\n")
	b.WriteString("// R-EXE-9: only built-in k6 modules are imported; nothing is fetched at runtime.\n")
	b.WriteString("import http from 'k6/http';\n")
	b.WriteString("import exec from 'k6/execution';\n\n")

	b.WriteString("export const options = {\n  scenarios: {\n")
	b.WriteString("    load: {\n")
	b.WriteString("      executor: 'ramping-arrival-rate',\n")
	b.WriteString("      exec: 'run',\n")
	b.WriteString("      startRate: 0,\n")
	b.WriteString("      timeUnit: '1s',\n")
	fmt.Fprintf(&b, "      preAllocatedVUs: %d,\n", preAllocated)
	fmt.Fprintf(&b, "      maxVUs: %d,\n", maxVUs)
	b.WriteString("      stages: [\n")
	for _, s := range stages {
		fmt.Fprintf(&b, "        { target: %s, duration: %q },\n", formatRate(s.Target), s.Duration)
	}
	b.WriteString("      ],\n")
	b.WriteString("    },\n")

	for _, s := range stages {
		fmt.Fprintf(&b, "    phase_%s: {\n", s.Phase)
		b.WriteString("      executor: 'shared-iterations',\n")
		b.WriteString("      exec: 'markPhase',\n")
		b.WriteString("      vus: 1,\n")
		b.WriteString("      iterations: 1,\n")
		fmt.Fprintf(&b, "      startTime: %q,\n", s.StartAt.String())
		fmt.Fprintf(&b, "      tags: { phase: %q },\n", s.Phase)
		b.WriteString("    },\n")
	}
	b.WriteString("  },\n};\n\n")

	fmt.Fprintf(&b, "export function markPhase() {\n  console.log(%q + ' ' + exec.scenario.name.replace('phase_', '') + ' ' + Date.now());\n}\n\n", PhaseMarkerPrefix)

	fmt.Fprintf(&b, "const scenarios = %s;\n\n", scenarios)
	b.WriteString(runFunctionJS)

	return b.String(), nil
}

func resolveStages(cfgStages []config.Stage) ([]compiledStage, float64, error) {
	var stages []compiledStage
	var cursor time.Duration
	maxTarget := 0.0
	for _, s := range cfgStages {
		targetStr, durStr := s.To, s.Over
		if s.To == "" {
			targetStr, durStr = s.Hold, s.For
		}
		target, err := parseRPS(targetStr)
		if err != nil {
			return nil, 0, fmt.Errorf("k6: stage %q: %w", s.Phase, err)
		}
		dur, err := time.ParseDuration(durStr)
		if err != nil {
			return nil, 0, fmt.Errorf("k6: stage %q: invalid duration %q: %w", s.Phase, durStr, err)
		}
		stages = append(stages, compiledStage{Phase: s.Phase, Target: target, Duration: durStr, StartAt: cursor})
		cursor += dur
		if target > maxTarget {
			maxTarget = target
		}
	}
	return stages, maxTarget, nil
}

func formatRate(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

// jsFlow and jsScenario are the shapes embedded as a JS literal for the
// generated script's run() function to walk (R-CFG-9).
type jsFlow struct {
	Method string `json:"method"`
	URL    string `json:"url"`
	Body   string `json:"body,omitempty"`
}

type jsScenario struct {
	Name   string   `json:"name"`
	Weight int      `json:"weight"`
	Flow   []jsFlow `json:"flow"`
}

func scenariosJSON(scenarios []config.Scenario, baseURL string) (string, error) {
	out := make([]jsScenario, 0, len(scenarios))
	for _, s := range scenarios {
		flow := make([]jsFlow, 0, len(s.Flow))
		for _, step := range s.Flow {
			flow = append(flow, jsFlow{
				Method: strings.ToUpper(step.Method),
				URL:    baseURL + step.Path,
				Body:   step.Body,
			})
		}
		out = append(out, jsScenario{Name: s.Name, Weight: s.Weight, Flow: flow})
	}
	b, err := json.Marshal(out)
	if err != nil {
		return "", fmt.Errorf("k6: marshal scenarios: %w", err)
	}
	return string(b), nil
}

// runFunctionJS is the fixed body every generated script shares: pick a
// scenario weighted by load.scenarios[].weight, then replay its flow as k6
// http calls (R-CFG-9). It is inlined, not fetched (R-EXE-9).
const runFunctionJS = `function pickScenario() {
  const total = scenarios.reduce((sum, s) => sum + s.weight, 0);
  let r = Math.random() * total;
  for (const s of scenarios) {
    if (r < s.weight) return s;
    r -= s.weight;
  }
  return scenarios[scenarios.length - 1];
}

export function run() {
  const s = pickScenario();
  for (const step of s.flow) {
    http.request(step.method, step.url, step.body || null);
  }
}
`
