package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/jdb316/tortureu/internal/detect"
)

// initOutput is the torture.yaml content init derives from detection
// (R-DET-4, R-CFG-3/4/5), plus the gaps it found — detection gaps are
// surfaced, never hidden (R-DET-7).
//
// It is deliberately partial: R-DET-1 bounds detection to compose files and
// language manifests, never source, so init cannot infer load:, faults:, or
// assert: content. Filling those in is left to the human or agent (D-3);
// SPEC.md does not ask init to produce a runnable scenario, only the
// detected target/egress facts.
type initOutput struct {
	YAML []byte
	Gaps []string
}

// buildInit renders sys into a torture.yaml skeleton. composePath is
// recorded verbatim as target.compose (R-CFG-3).
//
// Egress hosts detect found in the compose graph (class: internal, R-DET-4)
// are written with that class. Every other host is left out of hosts:
// entirely rather than assigned a guessed class: an omitted host is
// unclassified by egress.Classify's own default-deny rule, so the first
// `tortureu run` refuses to start (R-DC2-2) instead of silently trusting a
// classification init invented. Each omitted host is also reported as a
// gap so it is visible, not just structurally enforced.
func buildInit(sys *detect.System, composePath string) initOutput {
	var b strings.Builder
	b.WriteString("# torture.yaml — generated by `tortureu init`\n")
	b.WriteString("#\n")
	b.WriteString("# target and egress below are detected from docker-compose.yml and language\n")
	b.WriteString("# manifests only (R-DET-1) — never source — so load:, faults:, and assert: are\n")
	b.WriteString("# not generated. Add them before `tortureu run`; a scenario with no assert: is\n")
	b.WriteString("# rejected (a run that cannot fail is not a test).\n\n")
	b.WriteString("version: 0\n\n")
	fmt.Fprintf(&b, "target:\n  compose: %s\n  service: %s\n\n", composePath, sys.SUT)

	var hosts []string
	for h := range sys.EgressClass {
		hosts = append(hosts, h)
	}
	sort.Strings(hosts)

	var gaps []string
	b.WriteString("egress:\n  default: deny\n  hosts:\n")
	for _, h := range hosts {
		if sys.EgressClass[h] == "internal" {
			fmt.Fprintf(&b, "    %s: { class: internal }\n", h)
			continue
		}
		fmt.Fprintf(&b, "    # %s: left UNCLASSIFIED — classify before `tortureu run` (DC-2 default-deny)\n", h)
		gaps = append(gaps, fmt.Sprintf("unclassified egress host: %s", h))
	}
	b.WriteString("\n")

	gaps = append(gaps, sys.Gaps...)

	return initOutput{YAML: []byte(b.String()), Gaps: gaps}
}

// runInit is the `tortureu init` verb: detect the stack, write torture.yaml
// (R-CLI-1). It never touches any file other than -out (R-DC1-3: init must
// not unregister or modify another tool's MCP registration — trivially
// true here since nothing else is written).
func runInit(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(stderr)
	compose := fs.String("compose", "docker-compose.yml", "path to the compose file to detect")
	out := fs.String("out", "torture.yaml", "path to write the generated config")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	sys, err := detect.Detect(*compose)
	if err != nil {
		fmt.Fprintf(stderr, "tortureu init: detect: %v\n", err)
		return 2
	}

	result := buildInit(sys, *compose)
	if err := os.WriteFile(*out, result.YAML, 0o644); err != nil {
		fmt.Fprintf(stderr, "tortureu init: write %s: %v\n", *out, err)
		return 2
	}

	fmt.Fprintf(stdout, "wrote %s\n", *out)
	if len(result.Gaps) > 0 {
		fmt.Fprintln(stdout, "\ngaps (not hidden — R-DET-7):")
		for _, g := range result.Gaps {
			fmt.Fprintf(stdout, "  - %s\n", g)
		}
	}
	return 0
}
