package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jdb316/tortureu/internal/ci"
	"github.com/jdb316/tortureu/internal/detect"
)

// initOutput is the torture.yaml content init derives from detection
// (R-DET-4, R-CFG-3/4/5), plus the gaps it found — detection gaps are
// surfaced, never hidden (R-DET-7).
//
// target and egress are genuinely detected. load: and assert: cannot be —
// R-DET-1 bounds detection to compose files and language manifests, never
// source, so init cannot know real scenarios or endpoints. R-CLI-4 requires
// the file to be runnable anyway, so buildInit fills those two blocks with
// a deliberately generic, deliberately low-rate starter (see starter
// constants below) clearly marked for editing, rather than leaving `run`
// to reject the file outright.
type initOutput struct {
	YAML []byte
	Gaps []string
}

// Starter load profile (R-CLI-4): a single low-rate ramp against "/" — the
// one path every HTTP service is likely to expose without fabricating a
// real endpoint — held long enough for a handful of requests, plus a
// conservative latency and error-rate assert. "Low" is the point: this file
// may be run by someone who has not yet read what it does, so the default
// must be unable to hurt anything it touches.
const (
	starterRatePerSec = "2rps"
	starterRampOver   = "10s"
)

// buildInit renders sys into a runnable torture.yaml (R-CLI-4). composePath
// is recorded verbatim as target.compose (R-CFG-3).
//
// Egress hosts detect found in the compose graph (class: internal, R-DET-4)
// are written with that class. Every other host is left out of hosts:
// entirely rather than assigned a guessed class: an omitted host is
// unclassified by egress.Classify's own default-deny rule, so the first
// `tortureu run` refuses to start (R-DC2-2) instead of silently trusting a
// classification init invented. Each omitted host is also reported as a
// gap so it is visible, not just structurally enforced.
func buildInit(sys *detect.System, composePath string) initOutput {
	var b strings.Builder
	b.WriteString("# torture.yaml — generated by `tortureu init`\n")
	b.WriteString("#\n")
	b.WriteString("# target and egress below are detected from docker-compose.yml and language\n")
	b.WriteString("# manifests only (R-DET-1) — never source — so this file cannot know your real\n")
	b.WriteString("# scenarios or endpoints. load: and assert: are a generic, low-rate starter\n")
	b.WriteString("# (R-CLI-4): it runs, it asserts something conservative, and it is meant to be\n")
	b.WriteString("# edited into a scenario that reflects what this service actually does.\n\n")
	b.WriteString("version: 0\n\n")

	var gaps []string
	b.WriteString("target:\n")
	fmt.Fprintf(&b, "  compose: %s\n", composePath)
	if sys.SUT != "" {
		fmt.Fprintf(&b, "  service: %s\n", sys.SUT)
	} else {
		// R-CLI-4: never write an empty required field. `service: ` with
		// nothing after it is syntactically a present, empty YAML value —
		// config.Parse's own emptiness check would then reject it with a
		// plain "target.service is required" (fine, and no worse than
		// today), but a blank field that still visually looks like a
		// filled-in file is exactly the "looks complete but isn't" failure
		// this requirement exists to prevent. Detection found no compose
		// service with build: (R-DET-2/8): there is genuinely nothing to
		// name, so the key is left out entirely — commented, not blank —
		// and the gap is surfaced the same way an unclassified host is
		// (in the file, and on stdout via the Gaps list), not guessed.
		b.WriteString("  # no system under test detected — no compose service declares build:.\n")
		b.WriteString("  # name it yourself: service: <compose-service-name> (see R-DET-8)\n")
		gaps = append(gaps, "no system under test detected: no compose service declares build: — target.service must be set by hand")
	}

	gaps = append(gaps, writeBaseURL(&b, sys)...)

	var hosts []string
	for h := range sys.EgressClass {
		hosts = append(hosts, h)
	}
	sort.Strings(hosts)

	b.WriteString("egress:\n  default: deny\n  hosts:\n")
	for _, h := range hosts {
		if sys.EgressClass[h] == "internal" {
			fmt.Fprintf(&b, "    %s: { class: internal }\n", h)
			continue
		}
		fmt.Fprintf(&b, "    # %s: left UNCLASSIFIED — classify before `tortureu run` (DC-2 default-deny)\n", h)
		gaps = append(gaps, fmt.Sprintf("unclassified egress host: %s", h))
	}
	b.WriteString("\n")

	b.WriteString("# STARTER — generic and deliberately low-rate (R-CLI-4). Edit the scenario\n")
	b.WriteString("# below (and the assert: thresholds) once you know the endpoints that matter.\n")
	b.WriteString("load:\n")
	b.WriteString("  engine: k6\n")
	b.WriteString("  model: arrival_rate\n")
	b.WriteString("  stages:\n")
	fmt.Fprintf(&b, "    - phase: starter\n      to: %s\n      over: %s\n", starterRatePerSec, starterRampOver)
	b.WriteString("  scenarios:\n")
	b.WriteString("    - name: starter\n")
	b.WriteString("      weight: 100\n")
	b.WriteString("      flow:\n")
	b.WriteString("        - { method: GET, path: / }\n\n")

	b.WriteString("assert:\n")
	b.WriteString("  - http_req_duration: [\"p(95)<1000\"]\n")
	b.WriteString("  - http_req_failed:   [\"rate<0.01\"]\n\n")

	gaps = append(gaps, sys.Gaps...)

	return initOutput{YAML: []byte(b.String()), Gaps: gaps}
}

// writeBaseURL writes target.base_url, or an explanation of why it could
// not be written, and returns the gaps that go with it (R-CLI-19). It
// closes the target: block with a blank line either way.
//
// The rule is a three-way split on how many ports the SUT declares
// (R-DET-16), and only the first case produces a value:
//
//	one     → base_url, with its two assumptions named
//	several → nothing, every candidate named for the user to choose from
//	none    → nothing, and what that means said out loud
//
// The URL is http://localhost:<container port>, not the published host
// port: `run` dials it from inside the SUT container's own network
// namespace, where the SUT's loopback is the SUT and the published port is
// not bound (see internal/run/load.go). Getting this backwards is the one
// mistake here with teeth — for an asymmetric mapping like E1's own
// "8081:8080" it produces a file that looks detected, runs, and fails every
// single request.
//
// Picking among several would be nearly as bad: it looks detected too, and
// measures whatever answers on a debugger or admin port. An empty base_url
// is instead R-EXE-28's loud refusal, which names the field — so a missing
// value costs one edit, and a wrong one costs a verdict about the wrong
// process.
func writeBaseURL(b *strings.Builder, sys *detect.System) []string {
	defer b.WriteString("\n")

	urls := make([]string, 0, len(sys.SUTPorts))
	for _, port := range sys.SUTPorts {
		urls = append(urls, "http://localhost:"+port)
	}

	switch len(urls) {
	case 1:
		fmt.Fprintf(b, "  base_url: %s\n", urls[0])
		// Two assumptions, both stated: the scheme (compose says nothing
		// about TLS, and a port number is not evidence of it — reading 443
		// as https would be a guess dressed as detection), and loopback
		// binding.
		fmt.Fprintf(b, "  # base_url uses the port %s declares in the compose file, dialled on\n", sys.SUT)
		b.WriteString("  # localhost because load runs inside that container's own network\n")
		b.WriteString("  # namespace. Two assumptions: that the service speaks http:// rather\n")
		b.WriteString("  # than TLS, and that it listens on loopback and not only on its\n")
		b.WriteString("  # container IP. Change it if either is wrong for this service.\n")
		return nil

	case 0:
		if sys.SUT == "" {
			// No SUT at all: the missing service: above is already the gap
			// to fix, and naming a second one here would just be noise.
			b.WriteString("  # base_url: not derivable — no system under test was detected (see above).\n")
			return []string{"target.base_url not written: no system under test was detected — set both service: and base_url: by hand"}
		}
		fmt.Fprintf(b, "  # base_url: NOT DETECTED — the compose file declares no port for %s\n", sys.SUT)
		b.WriteString("  # (no ports: and no expose:), so there is nothing to derive it from.\n")
		b.WriteString("  # Set the port the service actually listens on:\n")
		b.WriteString("  #   base_url: http://localhost:<port>\n")
		return []string{fmt.Sprintf(
			"target.base_url not written: compose declares no port for SUT %s (nothing to derive it from) — set it by hand before `tortureu run`", sys.SUT)}

	default:
		fmt.Fprintf(b, "  # base_url: NOT CHOSEN — %s declares %d ports, and compose does not say\n", sys.SUT, len(urls))
		b.WriteString("  # which one serves the traffic you want measured. Uncomment one (http://\n")
		b.WriteString("  # is an assumption; localhost is where load runs, inside this\n")
		b.WriteString("  # container's own network namespace):\n")
		for _, u := range urls {
			fmt.Fprintf(b, "  #   base_url: %s\n", u)
		}
		return []string{fmt.Sprintf(
			"target.base_url not written: SUT %s declares %d ports (%s) — pick one; guessing could point load at a debugger or admin port",
			sys.SUT, len(urls), strings.Join(urls, ", "))}
	}
}

// runInitCI implements `tortureu init --ci [provider]` (R-CLI-11): write a CI
// pipeline whose contract is R-VER-7's exit codes. It is a mode, not a
// modifier — no detection runs and no torture.yaml is written, because the
// two artefacts have different lifetimes (a config is regenerated as the
// stack changes; a pipeline is written once and then hand-edited).
//
// The generated content lives in internal/ci, not here, so the pipeline can
// be parsed and its shell executed by tests without going through the CLI.
func runInitCI(args []string, ciOut string, stdout, stderr io.Writer) int {
	provider := ci.ProviderGitHub
	switch len(args) {
	case 0:
	case 1:
		provider = args[0]
	default:
		fmt.Fprintf(stderr, "tortureu init --ci: expected at most one provider, got %v\n", args)
		return 2
	}

	path, content, err := ci.Generate(provider)
	if err != nil {
		fmt.Fprintf(stderr, "tortureu init --ci: %v\n", err)
		return 2
	}
	if ciOut != "" {
		path = ciOut
	}

	// Refuse rather than overwrite (R-CLI-11). A pipeline carries hand-made
	// edits — runner labels, secrets, the install step — that init cannot
	// regenerate, so replacing it silently destroys work. Stat-then-write is
	// racy in principle; O_EXCL below is the real guard, and this check
	// exists to produce the specific message.
	if _, err := os.Stat(path); err == nil {
		fmt.Fprintf(stderr, "tortureu init --ci: %s already exists; refusing to overwrite it.\n"+
			"Move it aside, or write elsewhere with -ci-out.\n", path)
		return 2
	} else if !os.IsNotExist(err) {
		fmt.Fprintf(stderr, "tortureu init --ci: %s: %v\n", path, err)
		return 2
	}

	if dir := filepath.Dir(path); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			fmt.Fprintf(stderr, "tortureu init --ci: create %s: %v\n", dir, err)
			return 2
		}
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		fmt.Fprintf(stderr, "tortureu init --ci: write %s: %v\n", path, err)
		return 2
	}
	if _, err := f.Write(content); err != nil {
		_ = f.Close()
		fmt.Fprintf(stderr, "tortureu init --ci: write %s: %v\n", path, err)
		return 2
	}
	if err := f.Close(); err != nil {
		fmt.Fprintf(stderr, "tortureu init --ci: write %s: %v\n", path, err)
		return 2
	}

	fmt.Fprintf(stdout, "wrote %s\n", path)
	fmt.Fprintln(stdout, "\nthe pipeline treats VERDICT.md §2 exit codes 0-4 as the contract:")
	fmt.Fprintln(stdout, "  0 pass · 1 assertion broke · 2 harness error · 3 aborted · 4 inconclusive")
	fmt.Fprintln(stdout, "  1, 2, 3 and 4 all fail the build — 4 included (R-VER-8)")
	fmt.Fprintln(stdout, "\ngaps (not hidden — R-DET-7):")
	if ci.ReleaseVersion == "" {
		fmt.Fprintln(stdout, "  - there is no published release to install: the install step therefore")
		fmt.Fprintln(stdout, "    FAILS the job with exit 2 (harness error) and names the install routes")
		fmt.Fprintln(stdout, "    (SPEC.md TBD-11). Pin one of them to a tag — until you do, this")
		fmt.Fprintln(stdout, "    pipeline is red on purpose rather than green having run nothing.")
	} else {
		fmt.Fprintf(stdout, "  - the install step pins tortureu %s and verifies what it downloads;\n", ci.ReleaseVersion)
		fmt.Fprintln(stdout, "    edit it if you install tortureu some other way.")
	}
	fmt.Fprintln(stdout, "  - the pipeline needs a torture.yaml — run `tortureu init` to generate one.")
	return 0
}

// runInit is the `tortureu init` verb: detect the stack, write torture.yaml
// (R-CLI-1). It never touches any file other than -out (R-DC1-3: init must
// not unregister or modify another tool's MCP registration — trivially
// true here since nothing else is written).
func runInit(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(stderr)
	compose := fs.String("compose", detect.DefaultComposePath, "path to the compose file to detect")
	out := fs.String("out", "torture.yaml", "path to write the generated config")
	// -ci is a bool, and the provider is the positional argument after it
	// (`tortureu init --ci gitlab`), because the flag has to work both bare
	// and with a value. A string flag cannot: `--ci` alone would be "flag
	// needs an argument".
	ciMode := fs.Bool("ci", false, "write a CI pipeline instead of torture.yaml; provider follows as an argument (github, gitlab; default github)")
	ciOut := fs.String("ci-out", "", "path to write the CI pipeline (default: the provider's conventional location)")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	if *ciMode {
		return runInitCI(fs.Args(), *ciOut, stdout, stderr)
	}

	// R-DET-15: an unset -compose resolves by the Compose Specification's
	// own precedence, so a repo using compose.yaml (the canonical name, and
	// what nearly every real project uses) works without a flag.
	composePath, cerr := detect.ResolveComposeArg(*compose)
	if cerr != nil {
		fmt.Fprintf(stderr, "tortureu init: %v\n", cerr)
		return 2
	}

	sys, err := detect.Detect(composePath)
	if err != nil {
		fmt.Fprintf(stderr, "tortureu init: detect: %v\n", err)
		return 2
	}

	result := buildInit(sys, composePath)
	if err := os.WriteFile(*out, result.YAML, 0o644); err != nil {
		fmt.Fprintf(stderr, "tortureu init: write %s: %v\n", *out, err)
		return 2
	}

	fmt.Fprintf(stdout, "wrote %s\n", *out)
	if len(result.Gaps) > 0 {
		fmt.Fprintln(stdout, "\ngaps (not hidden — R-DET-7):")
		for _, g := range result.Gaps {
			fmt.Fprintf(stdout, "  - %s\n", g)
		}
	}

	// A machine missing a prerequisite `run` needs (k6, docker, docker
	// compose) is a fact about this machine, not about the repo, so it is
	// warned about here rather than written into torture.yaml (which may
	// be committed and run elsewhere). init MUST warn without failing
	// (R-CLI-5): a config generated on a machine that cannot yet run it is
	// still useful — a known-unknown named up front, not discovered two
	// steps later at `run`.
	if missing := missingPrerequisites(checkPrerequisites()); len(missing) > 0 {
		fmt.Fprintln(stdout, "\nwarnings (this machine is missing what `run` needs):")
		for _, m := range missing {
			fmt.Fprintf(stdout, "  - %s: %s\n", m.Name, m.Hint)
		}
	}
	return 0
}
