package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/jdb316/tortureu/internal/detect"
)

// initOutput is the torture.yaml content init derives from detection
// (R-DET-4, R-CFG-3/4/5), plus the gaps it found — detection gaps are
// surfaced, never hidden (R-DET-7).
//
// target and egress are genuinely detected. load: and assert: cannot be —
// R-DET-1 bounds detection to compose files and language manifests, never
// source, so init cannot know real scenarios or endpoints. R-CLI-4 requires
// the file to be runnable anyway, so buildInit fills those two blocks with
// a deliberately generic, deliberately low-rate starter (see starter
// constants below) clearly marked for editing, rather than leaving `run`
// to reject the file outright.
type initOutput struct {
	YAML []byte
	Gaps []string
}

// Starter load profile (R-CLI-4): a single low-rate ramp against "/" — the
// one path every HTTP service is likely to expose without fabricating a
// real endpoint — held long enough for a handful of requests, plus a
// conservative latency and error-rate assert. "Low" is the point: this file
// may be run by someone who has not yet read what it does, so the default
// must be unable to hurt anything it touches.
const (
	starterRatePerSec = "2rps"
	starterRampOver   = "10s"
)

// buildInit renders sys into a runnable torture.yaml (R-CLI-4). composePath
// is recorded verbatim as target.compose (R-CFG-3).
//
// Egress hosts detect found in the compose graph (class: internal, R-DET-4)
// are written with that class. Every other host is left out of hosts:
// entirely rather than assigned a guessed class: an omitted host is
// unclassified by egress.Classify's own default-deny rule, so the first
// `tortureu run` refuses to start (R-DC2-2) instead of silently trusting a
// classification init invented. Each omitted host is also reported as a
// gap so it is visible, not just structurally enforced.
func buildInit(sys *detect.System, composePath string) initOutput {
	var b strings.Builder
	b.WriteString("# torture.yaml — generated by `tortureu init`\n")
	b.WriteString("#\n")
	b.WriteString("# target and egress below are detected from docker-compose.yml and language\n")
	b.WriteString("# manifests only (R-DET-1) — never source — so this file cannot know your real\n")
	b.WriteString("# scenarios or endpoints. load: and assert: are a generic, low-rate starter\n")
	b.WriteString("# (R-CLI-4): it runs, it asserts something conservative, and it is meant to be\n")
	b.WriteString("# edited into a scenario that reflects what this service actually does.\n\n")
	b.WriteString("version: 0\n\n")

	var gaps []string
	b.WriteString("target:\n")
	fmt.Fprintf(&b, "  compose: %s\n", composePath)
	if sys.SUT != "" {
		fmt.Fprintf(&b, "  service: %s\n\n", sys.SUT)
	} else {
		// R-CLI-4: never write an empty required field. `service: ` with
		// nothing after it is syntactically a present, empty YAML value —
		// config.Parse's own emptiness check would then reject it with a
		// plain "target.service is required" (fine, and no worse than
		// today), but a blank field that still visually looks like a
		// filled-in file is exactly the "looks complete but isn't" failure
		// this requirement exists to prevent. Detection found no compose
		// service with build: (R-DET-2/8): there is genuinely nothing to
		// name, so the key is left out entirely — commented, not blank —
		// and the gap is surfaced the same way an unclassified host is
		// (in the file, and on stdout via the Gaps list), not guessed.
		b.WriteString("  # no system under test detected — no compose service declares build:.\n")
		b.WriteString("  # name it yourself: service: <compose-service-name> (see R-DET-8)\n\n")
		gaps = append(gaps, "no system under test detected: no compose service declares build: — target.service must be set by hand")
	}

	var hosts []string
	for h := range sys.EgressClass {
		hosts = append(hosts, h)
	}
	sort.Strings(hosts)

	b.WriteString("egress:\n  default: deny\n  hosts:\n")
	for _, h := range hosts {
		if sys.EgressClass[h] == "internal" {
			fmt.Fprintf(&b, "    %s: { class: internal }\n", h)
			continue
		}
		fmt.Fprintf(&b, "    # %s: left UNCLASSIFIED — classify before `tortureu run` (DC-2 default-deny)\n", h)
		gaps = append(gaps, fmt.Sprintf("unclassified egress host: %s", h))
	}
	b.WriteString("\n")

	b.WriteString("# STARTER — generic and deliberately low-rate (R-CLI-4). Edit the scenario\n")
	b.WriteString("# below (and the assert: thresholds) once you know the endpoints that matter.\n")
	b.WriteString("load:\n")
	b.WriteString("  engine: k6\n")
	b.WriteString("  model: arrival_rate\n")
	b.WriteString("  stages:\n")
	fmt.Fprintf(&b, "    - phase: starter\n      to: %s\n      over: %s\n", starterRatePerSec, starterRampOver)
	b.WriteString("  scenarios:\n")
	b.WriteString("    - name: starter\n")
	b.WriteString("      weight: 100\n")
	b.WriteString("      flow:\n")
	b.WriteString("        - { method: GET, path: / }\n\n")

	b.WriteString("assert:\n")
	b.WriteString("  - http_req_duration: [\"p(95)<1000\"]\n")
	b.WriteString("  - http_req_failed:   [\"rate<0.01\"]\n\n")

	gaps = append(gaps, sys.Gaps...)

	return initOutput{YAML: []byte(b.String()), Gaps: gaps}
}

// runInit is the `tortureu init` verb: detect the stack, write torture.yaml
// (R-CLI-1). It never touches any file other than -out (R-DC1-3: init must
// not unregister or modify another tool's MCP registration — trivially
// true here since nothing else is written).
func runInit(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(stderr)
	compose := fs.String("compose", "docker-compose.yml", "path to the compose file to detect")
	out := fs.String("out", "torture.yaml", "path to write the generated config")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	sys, err := detect.Detect(*compose)
	if err != nil {
		fmt.Fprintf(stderr, "tortureu init: detect: %v\n", err)
		return 2
	}

	result := buildInit(sys, *compose)
	if err := os.WriteFile(*out, result.YAML, 0o644); err != nil {
		fmt.Fprintf(stderr, "tortureu init: write %s: %v\n", *out, err)
		return 2
	}

	fmt.Fprintf(stdout, "wrote %s\n", *out)
	if len(result.Gaps) > 0 {
		fmt.Fprintln(stdout, "\ngaps (not hidden — R-DET-7):")
		for _, g := range result.Gaps {
			fmt.Fprintf(stdout, "  - %s\n", g)
		}
	}
	return 0
}
